CREATE TABLE IF NOT EXISTS table_user
(
	user_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	account VARCHAR(64) NOT NULL,
	password_hash BINARY(32) NOT NULL,
	password_salt BINARY(16) NOT NULL,
	status TINYINT UNSIGNED NOT NULL DEFAULT 1,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (user_id),
	UNIQUE KEY uk_table_user_account (account)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
