// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: request.proto
// Protobuf C++ Version: 5.29.3

#ifndef request_2eproto_2epb_2eh
#define request_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/map.h"  // IWYU pragma: export
#include "google/protobuf/map_entry.h"
#include "google/protobuf/map_field_inl.h"
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_request_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_request_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_request_2eproto;
namespace request {
class RequestData;
struct RequestDataDefaultTypeInternal;
extern RequestDataDefaultTypeInternal _RequestData_default_instance_;
class RequestData_ExtraEntry_DoNotUse;
struct RequestData_ExtraEntry_DoNotUseDefaultTypeInternal;
extern RequestData_ExtraEntry_DoNotUseDefaultTypeInternal _RequestData_ExtraEntry_DoNotUse_default_instance_;
class RequestData_RetEntry_DoNotUse;
struct RequestData_RetEntry_DoNotUseDefaultTypeInternal;
extern RequestData_RetEntry_DoNotUseDefaultTypeInternal _RequestData_RetEntry_DoNotUse_default_instance_;
}  // namespace request
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace request {
enum RequestType : int {
  UNKNOWN = 0,
  QUERY_AUTH = 1,
  QUERY_USERINFO = 2,
  UPDATE_AUTH = 3,
  UPDAT_PRODUCT = 4,
  RequestType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  RequestType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool RequestType_IsValid(int value);
extern const uint32_t RequestType_internal_data_[];
constexpr RequestType RequestType_MIN = static_cast<RequestType>(0);
constexpr RequestType RequestType_MAX = static_cast<RequestType>(4);
constexpr int RequestType_ARRAYSIZE = 4 + 1;
const ::google::protobuf::EnumDescriptor*
RequestType_descriptor();
template <typename T>
const std::string& RequestType_Name(T value) {
  static_assert(std::is_same<T, RequestType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to RequestType_Name().");
  return RequestType_Name(static_cast<RequestType>(value));
}
template <>
inline const std::string& RequestType_Name(RequestType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<RequestType_descriptor,
                                                 0, 4>(
      static_cast<int>(value));
}
inline bool RequestType_Parse(absl::string_view name, RequestType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<RequestType>(
      RequestType_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class RequestData_RetEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<
          std::string, std::string,
          ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
          ::google::protobuf::internal::WireFormatLite::TYPE_STRING> {
 public:
  using SuperType = ::google::protobuf::internal::MapEntry<
      std::string, std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING>;
  RequestData_RetEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RequestData_RetEntry_DoNotUse(
      ::google::protobuf::internal::ConstantInitialized);
  explicit RequestData_RetEntry_DoNotUse(::google::protobuf::Arena* arena);
  static const RequestData_RetEntry_DoNotUse* internal_default_instance() {
    return reinterpret_cast<const RequestData_RetEntry_DoNotUse*>(
        &_RequestData_RetEntry_DoNotUse_default_instance_);
  }


 private:
  friend class ::google::protobuf::MessageLite;
  friend struct ::TableStruct_request_2eproto;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      45, 2>
      _table_;

  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;
};
// -------------------------------------------------------------------

class RequestData_ExtraEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<
          std::string, std::string,
          ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
          ::google::protobuf::internal::WireFormatLite::TYPE_STRING> {
 public:
  using SuperType = ::google::protobuf::internal::MapEntry<
      std::string, std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING>;
  RequestData_ExtraEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RequestData_ExtraEntry_DoNotUse(
      ::google::protobuf::internal::ConstantInitialized);
  explicit RequestData_ExtraEntry_DoNotUse(::google::protobuf::Arena* arena);
  static const RequestData_ExtraEntry_DoNotUse* internal_default_instance() {
    return reinterpret_cast<const RequestData_ExtraEntry_DoNotUse*>(
        &_RequestData_ExtraEntry_DoNotUse_default_instance_);
  }


 private:
  friend class ::google::protobuf::MessageLite;
  friend struct ::TableStruct_request_2eproto;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      47, 2>
      _table_;

  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;
};
// -------------------------------------------------------------------

class RequestData final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:request.RequestData) */ {
 public:
  inline RequestData() : RequestData(nullptr) {}
  ~RequestData() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RequestData* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RequestData));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RequestData(
      ::google::protobuf::internal::ConstantInitialized);

  inline RequestData(const RequestData& from) : RequestData(nullptr, from) {}
  inline RequestData(RequestData&& from) noexcept
      : RequestData(nullptr, std::move(from)) {}
  inline RequestData& operator=(const RequestData& from) {
    CopyFrom(from);
    return *this;
  }
  inline RequestData& operator=(RequestData&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RequestData& default_instance() {
    return *internal_default_instance();
  }
  static inline const RequestData* internal_default_instance() {
    return reinterpret_cast<const RequestData*>(
        &_RequestData_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(RequestData& a, RequestData& b) { a.Swap(&b); }
  inline void Swap(RequestData* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RequestData* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RequestData* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RequestData>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RequestData& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RequestData& from) { RequestData::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RequestData* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "request.RequestData"; }

 protected:
  explicit RequestData(::google::protobuf::Arena* arena);
  RequestData(::google::protobuf::Arena* arena, const RequestData& from);
  RequestData(::google::protobuf::Arena* arena, RequestData&& from) noexcept
      : RequestData(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kExtraFieldNumber = 3,
    kRetFieldNumber = 4,
    kCmdFieldNumber = 2,
    kTypeFieldNumber = 1,
  };
  // map<string, string> extra = 3;
  int extra_size() const;
  private:
  int _internal_extra_size() const;

  public:
  void clear_extra() ;
  const ::google::protobuf::Map<std::string, std::string>& extra() const;
  ::google::protobuf::Map<std::string, std::string>* mutable_extra();

  private:
  const ::google::protobuf::Map<std::string, std::string>& _internal_extra() const;
  ::google::protobuf::Map<std::string, std::string>* _internal_mutable_extra();

  public:
  // map<string, string> ret = 4;
  int ret_size() const;
  private:
  int _internal_ret_size() const;

  public:
  void clear_ret() ;
  const ::google::protobuf::Map<std::string, std::string>& ret() const;
  ::google::protobuf::Map<std::string, std::string>* mutable_ret();

  private:
  const ::google::protobuf::Map<std::string, std::string>& _internal_ret() const;
  ::google::protobuf::Map<std::string, std::string>* _internal_mutable_ret();

  public:
  // string cmd = 2;
  void clear_cmd() ;
  const std::string& cmd() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_cmd(Arg_&& arg, Args_... args);
  std::string* mutable_cmd();
  PROTOBUF_NODISCARD std::string* release_cmd();
  void set_allocated_cmd(std::string* value);

  private:
  const std::string& _internal_cmd() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_cmd(
      const std::string& value);
  std::string* _internal_mutable_cmd();

  public:
  // .request.RequestType type = 1;
  void clear_type() ;
  ::request::RequestType type() const;
  void set_type(::request::RequestType value);

  private:
  ::request::RequestType _internal_type() const;
  void _internal_set_type(::request::RequestType value);

  public:
  // @@protoc_insertion_point(class_scope:request.RequestData)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 4, 2,
      39, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const RequestData& from_msg);
    ::google::protobuf::internal::MapField<RequestData_ExtraEntry_DoNotUse, std::string, std::string,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING>
        extra_;
    ::google::protobuf::internal::MapField<RequestData_RetEntry_DoNotUse, std::string, std::string,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING>
        ret_;
    ::google::protobuf::internal::ArenaStringPtr cmd_;
    int type_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_request_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// RequestData

// .request.RequestType type = 1;
inline void RequestData::clear_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = 0;
}
inline ::request::RequestType RequestData::type() const {
  // @@protoc_insertion_point(field_get:request.RequestData.type)
  return _internal_type();
}
inline void RequestData::set_type(::request::RequestType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:request.RequestData.type)
}
inline ::request::RequestType RequestData::_internal_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::request::RequestType>(_impl_.type_);
}
inline void RequestData::_internal_set_type(::request::RequestType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = value;
}

// string cmd = 2;
inline void RequestData::clear_cmd() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cmd_.ClearToEmpty();
}
inline const std::string& RequestData::cmd() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:request.RequestData.cmd)
  return _internal_cmd();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void RequestData::set_cmd(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cmd_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:request.RequestData.cmd)
}
inline std::string* RequestData::mutable_cmd() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_cmd();
  // @@protoc_insertion_point(field_mutable:request.RequestData.cmd)
  return _s;
}
inline const std::string& RequestData::_internal_cmd() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.cmd_.Get();
}
inline void RequestData::_internal_set_cmd(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cmd_.Set(value, GetArena());
}
inline std::string* RequestData::_internal_mutable_cmd() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.cmd_.Mutable( GetArena());
}
inline std::string* RequestData::release_cmd() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:request.RequestData.cmd)
  return _impl_.cmd_.Release();
}
inline void RequestData::set_allocated_cmd(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cmd_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.cmd_.IsDefault()) {
    _impl_.cmd_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:request.RequestData.cmd)
}

// map<string, string> extra = 3;
inline int RequestData::_internal_extra_size() const {
  return _internal_extra().size();
}
inline int RequestData::extra_size() const {
  return _internal_extra_size();
}
inline void RequestData::clear_extra() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.extra_.Clear();
}
inline const ::google::protobuf::Map<std::string, std::string>& RequestData::_internal_extra() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.extra_.GetMap();
}
inline const ::google::protobuf::Map<std::string, std::string>& RequestData::extra() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:request.RequestData.extra)
  return _internal_extra();
}
inline ::google::protobuf::Map<std::string, std::string>* RequestData::_internal_mutable_extra() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.extra_.MutableMap();
}
inline ::google::protobuf::Map<std::string, std::string>* RequestData::mutable_extra() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_map:request.RequestData.extra)
  return _internal_mutable_extra();
}

// map<string, string> ret = 4;
inline int RequestData::_internal_ret_size() const {
  return _internal_ret().size();
}
inline int RequestData::ret_size() const {
  return _internal_ret_size();
}
inline void RequestData::clear_ret() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ret_.Clear();
}
inline const ::google::protobuf::Map<std::string, std::string>& RequestData::_internal_ret() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ret_.GetMap();
}
inline const ::google::protobuf::Map<std::string, std::string>& RequestData::ret() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:request.RequestData.ret)
  return _internal_ret();
}
inline ::google::protobuf::Map<std::string, std::string>* RequestData::_internal_mutable_ret() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.ret_.MutableMap();
}
inline ::google::protobuf::Map<std::string, std::string>* RequestData::mutable_ret() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_map:request.RequestData.ret)
  return _internal_mutable_ret();
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace request


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::request::RequestType> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::request::RequestType>() {
  return ::request::RequestType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // request_2eproto_2epb_2eh
