// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: request/request.proto
// Protobuf C++ Version: 5.29.3

#include "request/request.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace request {
              template <typename>
PROTOBUF_CONSTEXPR RequestData_RetEntry_DoNotUse::RequestData_RetEntry_DoNotUse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : RequestData_RetEntry_DoNotUse::MapEntry(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : RequestData_RetEntry_DoNotUse::MapEntry() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct RequestData_RetEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RequestData_RetEntry_DoNotUseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RequestData_RetEntry_DoNotUseDefaultTypeInternal() {}
  union {
    RequestData_RetEntry_DoNotUse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RequestData_RetEntry_DoNotUseDefaultTypeInternal _RequestData_RetEntry_DoNotUse_default_instance_;
              template <typename>
PROTOBUF_CONSTEXPR RequestData_ExtraEntry_DoNotUse::RequestData_ExtraEntry_DoNotUse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : RequestData_ExtraEntry_DoNotUse::MapEntry(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : RequestData_ExtraEntry_DoNotUse::MapEntry() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct RequestData_ExtraEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RequestData_ExtraEntry_DoNotUseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RequestData_ExtraEntry_DoNotUseDefaultTypeInternal() {}
  union {
    RequestData_ExtraEntry_DoNotUse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RequestData_ExtraEntry_DoNotUseDefaultTypeInternal _RequestData_ExtraEntry_DoNotUse_default_instance_;

inline constexpr RequestData::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : extra_{},
        ret_{},
        cmd_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        id_{::uint64_t{0u}},
        type_{static_cast< ::request::RequestType >(0)},
        payload_{},
        _cached_size_{0},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR RequestData::RequestData(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct RequestDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RequestDataDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RequestDataDefaultTypeInternal() {}
  union {
    RequestData _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RequestDataDefaultTypeInternal _RequestData_default_instance_;
}  // namespace request
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_request_2frequest_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_request_2frequest_2eproto = nullptr;
const ::uint32_t
    TableStruct_request_2frequest_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::request::RequestData_ExtraEntry_DoNotUse, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::request::RequestData_ExtraEntry_DoNotUse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::request::RequestData_ExtraEntry_DoNotUse, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::request::RequestData_ExtraEntry_DoNotUse, _impl_.value_),
        0,
        1,
        PROTOBUF_FIELD_OFFSET(::request::RequestData_RetEntry_DoNotUse, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::request::RequestData_RetEntry_DoNotUse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::request::RequestData_RetEntry_DoNotUse, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::request::RequestData_RetEntry_DoNotUse, _impl_.value_),
        0,
        1,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::request::RequestData, _internal_metadata_),
        ~0u,  // no _extensions_
        PROTOBUF_FIELD_OFFSET(::request::RequestData, _impl_._oneof_case_[0]),
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::request::RequestData, _impl_.type_),
        PROTOBUF_FIELD_OFFSET(::request::RequestData, _impl_.cmd_),
        PROTOBUF_FIELD_OFFSET(::request::RequestData, _impl_.extra_),
        PROTOBUF_FIELD_OFFSET(::request::RequestData, _impl_.ret_),
        PROTOBUF_FIELD_OFFSET(::request::RequestData, _impl_.id_),
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        PROTOBUF_FIELD_OFFSET(::request::RequestData, _impl_.payload_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 10, -1, sizeof(::request::RequestData_ExtraEntry_DoNotUse)},
        {12, 22, -1, sizeof(::request::RequestData_RetEntry_DoNotUse)},
        {24, -1, -1, sizeof(::request::RequestData)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::request::_RequestData_ExtraEntry_DoNotUse_default_instance_._instance,
    &::request::_RequestData_RetEntry_DoNotUse_default_instance_._instance,
    &::request::_RequestData_default_instance_._instance,
};
const char descriptor_table_protodef_request_2frequest_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\025request/request.proto\022\007request\032\030hqmark"
    "et/v1/market.proto\"\305\007\n\013RequestData\022\"\n\004ty"
    "pe\030\001 \001(\0162\024.request.RequestType\022\013\n\003cmd\030\002 "
    "\001(\t\022.\n\005extra\030\003 \003(\0132\037.request.RequestData"
    ".ExtraEntry\022*\n\003ret\030\004 \003(\0132\035.request.Reque"
    "stData.RetEntry\022\n\n\002id\030\005 \001(\004\0227\n\014auth_requ"
    "est\030\n \001(\0132\037.hqmarket.market.v1.AuthReque"
    "stH\000\022A\n\021subscribe_request\030\013 \001(\0132$.hqmark"
    "et.market.v1.SubscribeRequestH\000\022E\n\023unsub"
    "scribe_request\030\014 \001(\0132&.hqmarket.market.v"
    "1.UnsubscribeRequestH\000\022\?\n\020subscription_a"
    "ck\030\r \001(\0132#.hqmarket.market.v1.Subscripti"
    "onAckH\000\022.\n\005quote\030\016 \001(\0132\035.hqmarket.market"
    ".v1.QuoteDataH\000\022.\n\005depth\030\017 \001(\0132\035.hqmarke"
    "t.market.v1.DepthDataH\000\022.\n\005trade\030\020 \001(\0132\035"
    ".hqmarket.market.v1.TradeDataH\000\022*\n\003bar\030\021"
    " \001(\0132\033.hqmarket.market.v1.BarDataH\000\022=\n\rm"
    "arket_status\030\022 \001(\0132$.hqmarket.market.v1."
    "MarketStatusDataH\000\022A\n\017provider_status\030\023 "
    "\001(\0132&.hqmarket.market.v1.ProviderStatusD"
    "ataH\000\0229\n\rquery_request\030\024 \001(\0132 .hqmarket."
    "market.v1.QueryRequestH\000\022;\n\016query_respon"
    "se\030\025 \001(\0132!.hqmarket.market.v1.QueryRespo"
    "nseH\000\032,\n\nExtraEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005valu"
    "e\030\002 \001(\t:\0028\001\032*\n\010RetEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005"
    "value\030\002 \001(\t:\0028\001B\t\n\007payload*\177\n\013RequestTyp"
    "e\022\013\n\007UNKNOWN\020\000\022\016\n\nQUERY_AUTH\020\001\022\022\n\016QUERY_"
    "USERINFO\020\002\022\017\n\013UPDATE_AUTH\020\003\022\021\n\rUPDAT_PRO"
    "DUCT\020\004\022\014\n\010HQMARKET\020\005\022\r\n\tHEARTBEAT\020\006b\006pro"
    "to3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_request_2frequest_2eproto_deps[1] =
    {
        &::descriptor_table_hqmarket_2fv1_2fmarket_2eproto,
};
static ::absl::once_flag descriptor_table_request_2frequest_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_request_2frequest_2eproto = {
    false,
    false,
    1163,
    descriptor_table_protodef_request_2frequest_2eproto,
    "request/request.proto",
    &descriptor_table_request_2frequest_2eproto_once,
    descriptor_table_request_2frequest_2eproto_deps,
    1,
    3,
    schemas,
    file_default_instances,
    TableStruct_request_2frequest_2eproto::offsets,
    file_level_enum_descriptors_request_2frequest_2eproto,
    file_level_service_descriptors_request_2frequest_2eproto,
};
namespace request {
const ::google::protobuf::EnumDescriptor* RequestType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_request_2frequest_2eproto);
  return file_level_enum_descriptors_request_2frequest_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t RequestType_internal_data_[] = {
    458752u, 0u, };
bool RequestType_IsValid(int value) {
  return 0 <= value && value <= 6;
}
// ===================================================================

#if defined(PROTOBUF_CUSTOM_VTABLE)
              RequestData_ExtraEntry_DoNotUse::RequestData_ExtraEntry_DoNotUse() : SuperType(_class_data_.base()) {}
              RequestData_ExtraEntry_DoNotUse::RequestData_ExtraEntry_DoNotUse(::google::protobuf::Arena* arena)
                  : SuperType(arena, _class_data_.base()) {}
#else   // PROTOBUF_CUSTOM_VTABLE
              RequestData_ExtraEntry_DoNotUse::RequestData_ExtraEntry_DoNotUse() : SuperType() {}
              RequestData_ExtraEntry_DoNotUse::RequestData_ExtraEntry_DoNotUse(::google::protobuf::Arena* arena) : SuperType(arena) {}
#endif  // PROTOBUF_CUSTOM_VTABLE
              inline void* RequestData_ExtraEntry_DoNotUse::PlacementNew_(const void*, void* mem,
                                                      ::google::protobuf::Arena* arena) {
                return ::new (mem) RequestData_ExtraEntry_DoNotUse(arena);
              }
              constexpr auto RequestData_ExtraEntry_DoNotUse::InternalNewImpl_() {
                return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(RequestData_ExtraEntry_DoNotUse),
                                                          alignof(RequestData_ExtraEntry_DoNotUse));
              }
              PROTOBUF_CONSTINIT
              PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
              const ::google::protobuf::internal::ClassDataFull RequestData_ExtraEntry_DoNotUse::_class_data_ = {
                  ::google::protobuf::internal::ClassData{
                      &_RequestData_ExtraEntry_DoNotUse_default_instance_._instance,
                      &_table_.header,
                      nullptr,  // OnDemandRegisterArenaDtor
                      nullptr,  // IsInitialized
                      &RequestData_ExtraEntry_DoNotUse::MergeImpl,
                      ::google::protobuf::Message::GetNewImpl<RequestData_ExtraEntry_DoNotUse>(),
              #if defined(PROTOBUF_CUSTOM_VTABLE)
                      &RequestData_ExtraEntry_DoNotUse::SharedDtor,
                      static_cast<void (::google::protobuf::MessageLite::*)()>(
                          &RequestData_ExtraEntry_DoNotUse::ClearImpl),
                          ::google::protobuf::Message::ByteSizeLongImpl, ::google::protobuf::Message::_InternalSerializeImpl
                          ,
              #endif  // PROTOBUF_CUSTOM_VTABLE
                      PROTOBUF_FIELD_OFFSET(RequestData_ExtraEntry_DoNotUse, _impl_._cached_size_),
                      false,
                  },
                  &RequestData_ExtraEntry_DoNotUse::kDescriptorMethods,
                  &descriptor_table_request_2frequest_2eproto,
                  nullptr,  // tracker
              };
              const ::google::protobuf::internal::ClassData* RequestData_ExtraEntry_DoNotUse::GetClassData() const {
                ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
                ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
                return _class_data_.base();
              }
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 47, 2> RequestData_ExtraEntry_DoNotUse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(RequestData_ExtraEntry_DoNotUse, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::DiscardEverythingFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::request::RequestData_ExtraEntry_DoNotUse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string value = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(RequestData_ExtraEntry_DoNotUse, _impl_.value_)}},
    // string key = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(RequestData_ExtraEntry_DoNotUse, _impl_.key_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string key = 1;
    {PROTOBUF_FIELD_OFFSET(RequestData_ExtraEntry_DoNotUse, _impl_.key_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string value = 2;
    {PROTOBUF_FIELD_OFFSET(RequestData_ExtraEntry_DoNotUse, _impl_.value_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\36\3\5\0\0\0\0\0"
    "request.RequestData.ExtraEntry"
    "key"
    "value"
  }},
};

// ===================================================================

#if defined(PROTOBUF_CUSTOM_VTABLE)
              RequestData_RetEntry_DoNotUse::RequestData_RetEntry_DoNotUse() : SuperType(_class_data_.base()) {}
              RequestData_RetEntry_DoNotUse::RequestData_RetEntry_DoNotUse(::google::protobuf::Arena* arena)
                  : SuperType(arena, _class_data_.base()) {}
#else   // PROTOBUF_CUSTOM_VTABLE
              RequestData_RetEntry_DoNotUse::RequestData_RetEntry_DoNotUse() : SuperType() {}
              RequestData_RetEntry_DoNotUse::RequestData_RetEntry_DoNotUse(::google::protobuf::Arena* arena) : SuperType(arena) {}
#endif  // PROTOBUF_CUSTOM_VTABLE
              inline void* RequestData_RetEntry_DoNotUse::PlacementNew_(const void*, void* mem,
                                                      ::google::protobuf::Arena* arena) {
                return ::new (mem) RequestData_RetEntry_DoNotUse(arena);
              }
              constexpr auto RequestData_RetEntry_DoNotUse::InternalNewImpl_() {
                return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(RequestData_RetEntry_DoNotUse),
                                                          alignof(RequestData_RetEntry_DoNotUse));
              }
              PROTOBUF_CONSTINIT
              PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
              const ::google::protobuf::internal::ClassDataFull RequestData_RetEntry_DoNotUse::_class_data_ = {
                  ::google::protobuf::internal::ClassData{
                      &_RequestData_RetEntry_DoNotUse_default_instance_._instance,
                      &_table_.header,
                      nullptr,  // OnDemandRegisterArenaDtor
                      nullptr,  // IsInitialized
                      &RequestData_RetEntry_DoNotUse::MergeImpl,
                      ::google::protobuf::Message::GetNewImpl<RequestData_RetEntry_DoNotUse>(),
              #if defined(PROTOBUF_CUSTOM_VTABLE)
                      &RequestData_RetEntry_DoNotUse::SharedDtor,
                      static_cast<void (::google::protobuf::MessageLite::*)()>(
                          &RequestData_RetEntry_DoNotUse::ClearImpl),
                          ::google::protobuf::Message::ByteSizeLongImpl, ::google::protobuf::Message::_InternalSerializeImpl
                          ,
              #endif  // PROTOBUF_CUSTOM_VTABLE
                      PROTOBUF_FIELD_OFFSET(RequestData_RetEntry_DoNotUse, _impl_._cached_size_),
                      false,
                  },
                  &RequestData_RetEntry_DoNotUse::kDescriptorMethods,
                  &descriptor_table_request_2frequest_2eproto,
                  nullptr,  // tracker
              };
              const ::google::protobuf::internal::ClassData* RequestData_RetEntry_DoNotUse::GetClassData() const {
                ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
                ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
                return _class_data_.base();
              }
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 45, 2> RequestData_RetEntry_DoNotUse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(RequestData_RetEntry_DoNotUse, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::DiscardEverythingFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::request::RequestData_RetEntry_DoNotUse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string value = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(RequestData_RetEntry_DoNotUse, _impl_.value_)}},
    // string key = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(RequestData_RetEntry_DoNotUse, _impl_.key_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string key = 1;
    {PROTOBUF_FIELD_OFFSET(RequestData_RetEntry_DoNotUse, _impl_.key_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string value = 2;
    {PROTOBUF_FIELD_OFFSET(RequestData_RetEntry_DoNotUse, _impl_.value_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\34\3\5\0\0\0\0\0"
    "request.RequestData.RetEntry"
    "key"
    "value"
  }},
};

// ===================================================================

class RequestData::_Internal {
 public:
  static constexpr ::int32_t kOneofCaseOffset =
      PROTOBUF_FIELD_OFFSET(::request::RequestData, _impl_._oneof_case_);
};

void RequestData::set_allocated_auth_request(::hqmarket::market::v1::AuthRequest* auth_request) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (auth_request) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(auth_request)->GetArena();
    if (message_arena != submessage_arena) {
      auth_request = ::google::protobuf::internal::GetOwnedMessage(message_arena, auth_request, submessage_arena);
    }
    set_has_auth_request();
    _impl_.payload_.auth_request_ = auth_request;
  }
  // @@protoc_insertion_point(field_set_allocated:request.RequestData.auth_request)
}
void RequestData::clear_auth_request() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kAuthRequest) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.auth_request_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.auth_request_);
    }
    clear_has_payload();
  }
}
void RequestData::set_allocated_subscribe_request(::hqmarket::market::v1::SubscribeRequest* subscribe_request) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (subscribe_request) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(subscribe_request)->GetArena();
    if (message_arena != submessage_arena) {
      subscribe_request = ::google::protobuf::internal::GetOwnedMessage(message_arena, subscribe_request, submessage_arena);
    }
    set_has_subscribe_request();
    _impl_.payload_.subscribe_request_ = subscribe_request;
  }
  // @@protoc_insertion_point(field_set_allocated:request.RequestData.subscribe_request)
}
void RequestData::clear_subscribe_request() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kSubscribeRequest) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.subscribe_request_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.subscribe_request_);
    }
    clear_has_payload();
  }
}
void RequestData::set_allocated_unsubscribe_request(::hqmarket::market::v1::UnsubscribeRequest* unsubscribe_request) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (unsubscribe_request) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(unsubscribe_request)->GetArena();
    if (message_arena != submessage_arena) {
      unsubscribe_request = ::google::protobuf::internal::GetOwnedMessage(message_arena, unsubscribe_request, submessage_arena);
    }
    set_has_unsubscribe_request();
    _impl_.payload_.unsubscribe_request_ = unsubscribe_request;
  }
  // @@protoc_insertion_point(field_set_allocated:request.RequestData.unsubscribe_request)
}
void RequestData::clear_unsubscribe_request() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kUnsubscribeRequest) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.unsubscribe_request_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.unsubscribe_request_);
    }
    clear_has_payload();
  }
}
void RequestData::set_allocated_subscription_ack(::hqmarket::market::v1::SubscriptionAck* subscription_ack) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (subscription_ack) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(subscription_ack)->GetArena();
    if (message_arena != submessage_arena) {
      subscription_ack = ::google::protobuf::internal::GetOwnedMessage(message_arena, subscription_ack, submessage_arena);
    }
    set_has_subscription_ack();
    _impl_.payload_.subscription_ack_ = subscription_ack;
  }
  // @@protoc_insertion_point(field_set_allocated:request.RequestData.subscription_ack)
}
void RequestData::clear_subscription_ack() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kSubscriptionAck) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.subscription_ack_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.subscription_ack_);
    }
    clear_has_payload();
  }
}
void RequestData::set_allocated_quote(::hqmarket::market::v1::QuoteData* quote) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (quote) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(quote)->GetArena();
    if (message_arena != submessage_arena) {
      quote = ::google::protobuf::internal::GetOwnedMessage(message_arena, quote, submessage_arena);
    }
    set_has_quote();
    _impl_.payload_.quote_ = quote;
  }
  // @@protoc_insertion_point(field_set_allocated:request.RequestData.quote)
}
void RequestData::clear_quote() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kQuote) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.quote_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.quote_);
    }
    clear_has_payload();
  }
}
void RequestData::set_allocated_depth(::hqmarket::market::v1::DepthData* depth) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (depth) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(depth)->GetArena();
    if (message_arena != submessage_arena) {
      depth = ::google::protobuf::internal::GetOwnedMessage(message_arena, depth, submessage_arena);
    }
    set_has_depth();
    _impl_.payload_.depth_ = depth;
  }
  // @@protoc_insertion_point(field_set_allocated:request.RequestData.depth)
}
void RequestData::clear_depth() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kDepth) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.depth_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.depth_);
    }
    clear_has_payload();
  }
}
void RequestData::set_allocated_trade(::hqmarket::market::v1::TradeData* trade) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (trade) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(trade)->GetArena();
    if (message_arena != submessage_arena) {
      trade = ::google::protobuf::internal::GetOwnedMessage(message_arena, trade, submessage_arena);
    }
    set_has_trade();
    _impl_.payload_.trade_ = trade;
  }
  // @@protoc_insertion_point(field_set_allocated:request.RequestData.trade)
}
void RequestData::clear_trade() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kTrade) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.trade_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.trade_);
    }
    clear_has_payload();
  }
}
void RequestData::set_allocated_bar(::hqmarket::market::v1::BarData* bar) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (bar) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(bar)->GetArena();
    if (message_arena != submessage_arena) {
      bar = ::google::protobuf::internal::GetOwnedMessage(message_arena, bar, submessage_arena);
    }
    set_has_bar();
    _impl_.payload_.bar_ = bar;
  }
  // @@protoc_insertion_point(field_set_allocated:request.RequestData.bar)
}
void RequestData::clear_bar() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kBar) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.bar_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.bar_);
    }
    clear_has_payload();
  }
}
void RequestData::set_allocated_market_status(::hqmarket::market::v1::MarketStatusData* market_status) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (market_status) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(market_status)->GetArena();
    if (message_arena != submessage_arena) {
      market_status = ::google::protobuf::internal::GetOwnedMessage(message_arena, market_status, submessage_arena);
    }
    set_has_market_status();
    _impl_.payload_.market_status_ = market_status;
  }
  // @@protoc_insertion_point(field_set_allocated:request.RequestData.market_status)
}
void RequestData::clear_market_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kMarketStatus) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.market_status_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.market_status_);
    }
    clear_has_payload();
  }
}
void RequestData::set_allocated_provider_status(::hqmarket::market::v1::ProviderStatusData* provider_status) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (provider_status) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(provider_status)->GetArena();
    if (message_arena != submessage_arena) {
      provider_status = ::google::protobuf::internal::GetOwnedMessage(message_arena, provider_status, submessage_arena);
    }
    set_has_provider_status();
    _impl_.payload_.provider_status_ = provider_status;
  }
  // @@protoc_insertion_point(field_set_allocated:request.RequestData.provider_status)
}
void RequestData::clear_provider_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kProviderStatus) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.provider_status_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.provider_status_);
    }
    clear_has_payload();
  }
}
void RequestData::set_allocated_query_request(::hqmarket::market::v1::QueryRequest* query_request) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (query_request) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(query_request)->GetArena();
    if (message_arena != submessage_arena) {
      query_request = ::google::protobuf::internal::GetOwnedMessage(message_arena, query_request, submessage_arena);
    }
    set_has_query_request();
    _impl_.payload_.query_request_ = query_request;
  }
  // @@protoc_insertion_point(field_set_allocated:request.RequestData.query_request)
}
void RequestData::clear_query_request() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kQueryRequest) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.query_request_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.query_request_);
    }
    clear_has_payload();
  }
}
void RequestData::set_allocated_query_response(::hqmarket::market::v1::QueryResponse* query_response) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (query_response) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(query_response)->GetArena();
    if (message_arena != submessage_arena) {
      query_response = ::google::protobuf::internal::GetOwnedMessage(message_arena, query_response, submessage_arena);
    }
    set_has_query_response();
    _impl_.payload_.query_response_ = query_response;
  }
  // @@protoc_insertion_point(field_set_allocated:request.RequestData.query_response)
}
void RequestData::clear_query_response() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kQueryResponse) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.query_response_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.query_response_);
    }
    clear_has_payload();
  }
}
RequestData::RequestData(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:request.RequestData)
}
inline PROTOBUF_NDEBUG_INLINE RequestData::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::request::RequestData& from_msg)
      : extra_{visibility, arena, from.extra_},
        ret_{visibility, arena, from.ret_},
        cmd_(arena, from.cmd_),
        payload_{},
        _cached_size_{0},
        _oneof_case_{from._oneof_case_[0]} {}

RequestData::RequestData(
    ::google::protobuf::Arena* arena,
    const RequestData& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  RequestData* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, id_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, id_),
           offsetof(Impl_, type_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::type_));
  switch (payload_case()) {
    case PAYLOAD_NOT_SET:
      break;
      case kAuthRequest:
        _impl_.payload_.auth_request_ = ::google::protobuf::Message::CopyConstruct<::hqmarket::market::v1::AuthRequest>(arena, *from._impl_.payload_.auth_request_);
        break;
      case kSubscribeRequest:
        _impl_.payload_.subscribe_request_ = ::google::protobuf::Message::CopyConstruct<::hqmarket::market::v1::SubscribeRequest>(arena, *from._impl_.payload_.subscribe_request_);
        break;
      case kUnsubscribeRequest:
        _impl_.payload_.unsubscribe_request_ = ::google::protobuf::Message::CopyConstruct<::hqmarket::market::v1::UnsubscribeRequest>(arena, *from._impl_.payload_.unsubscribe_request_);
        break;
      case kSubscriptionAck:
        _impl_.payload_.subscription_ack_ = ::google::protobuf::Message::CopyConstruct<::hqmarket::market::v1::SubscriptionAck>(arena, *from._impl_.payload_.subscription_ack_);
        break;
      case kQuote:
        _impl_.payload_.quote_ = ::google::protobuf::Message::CopyConstruct<::hqmarket::market::v1::QuoteData>(arena, *from._impl_.payload_.quote_);
        break;
      case kDepth:
        _impl_.payload_.depth_ = ::google::protobuf::Message::CopyConstruct<::hqmarket::market::v1::DepthData>(arena, *from._impl_.payload_.depth_);
        break;
      case kTrade:
        _impl_.payload_.trade_ = ::google::protobuf::Message::CopyConstruct<::hqmarket::market::v1::TradeData>(arena, *from._impl_.payload_.trade_);
        break;
      case kBar:
        _impl_.payload_.bar_ = ::google::protobuf::Message::CopyConstruct<::hqmarket::market::v1::BarData>(arena, *from._impl_.payload_.bar_);
        break;
      case kMarketStatus:
        _impl_.payload_.market_status_ = ::google::protobuf::Message::CopyConstruct<::hqmarket::market::v1::MarketStatusData>(arena, *from._impl_.payload_.market_status_);
        break;
      case kProviderStatus:
        _impl_.payload_.provider_status_ = ::google::protobuf::Message::CopyConstruct<::hqmarket::market::v1::ProviderStatusData>(arena, *from._impl_.payload_.provider_status_);
        break;
      case kQueryRequest:
        _impl_.payload_.query_request_ = ::google::protobuf::Message::CopyConstruct<::hqmarket::market::v1::QueryRequest>(arena, *from._impl_.payload_.query_request_);
        break;
      case kQueryResponse:
        _impl_.payload_.query_response_ = ::google::protobuf::Message::CopyConstruct<::hqmarket::market::v1::QueryResponse>(arena, *from._impl_.payload_.query_response_);
        break;
  }

  // @@protoc_insertion_point(copy_constructor:request.RequestData)
}
inline PROTOBUF_NDEBUG_INLINE RequestData::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : extra_{visibility, arena},
        ret_{visibility, arena},
        cmd_(arena),
        payload_{},
        _cached_size_{0},
        _oneof_case_{} {}

inline void RequestData::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, id_),
           0,
           offsetof(Impl_, type_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::type_));
}
RequestData::~RequestData() {
  // @@protoc_insertion_point(destructor:request.RequestData)
  SharedDtor(*this);
}
inline void RequestData::SharedDtor(MessageLite& self) {
  RequestData& this_ = static_cast<RequestData&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.cmd_.Destroy();
  if (this_.has_payload()) {
    this_.clear_payload();
  }
  this_._impl_.~Impl_();
}

void RequestData::clear_payload() {
// @@protoc_insertion_point(one_of_clear_start:request.RequestData)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch (payload_case()) {
    case kAuthRequest: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.auth_request_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.auth_request_);
      }
      break;
    }
    case kSubscribeRequest: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.subscribe_request_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.subscribe_request_);
      }
      break;
    }
    case kUnsubscribeRequest: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.unsubscribe_request_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.unsubscribe_request_);
      }
      break;
    }
    case kSubscriptionAck: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.subscription_ack_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.subscription_ack_);
      }
      break;
    }
    case kQuote: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.quote_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.quote_);
      }
      break;
    }
    case kDepth: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.depth_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.depth_);
      }
      break;
    }
    case kTrade: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.trade_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.trade_);
      }
      break;
    }
    case kBar: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.bar_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.bar_);
      }
      break;
    }
    case kMarketStatus: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.market_status_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.market_status_);
      }
      break;
    }
    case kProviderStatus: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.provider_status_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.provider_status_);
      }
      break;
    }
    case kQueryRequest: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.query_request_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.query_request_);
      }
      break;
    }
    case kQueryResponse: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.query_response_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.query_response_);
      }
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}


inline void* RequestData::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) RequestData(arena);
}
constexpr auto RequestData::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(RequestData, _impl_.extra_) +
          decltype(RequestData::_impl_.extra_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(RequestData, _impl_.extra_) +
          decltype(RequestData::_impl_.extra_)::
              InternalGetArenaOffsetAlt(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(RequestData, _impl_.ret_) +
          decltype(RequestData::_impl_.ret_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(RequestData, _impl_.ret_) +
          decltype(RequestData::_impl_.ret_)::
              InternalGetArenaOffsetAlt(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(RequestData), alignof(RequestData), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&RequestData::PlacementNew_,
                                 sizeof(RequestData),
                                 alignof(RequestData));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull RequestData::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_RequestData_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &RequestData::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<RequestData>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &RequestData::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<RequestData>(), &RequestData::ByteSizeLong,
            &RequestData::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(RequestData, _impl_._cached_size_),
        false,
    },
    &RequestData::kDescriptorMethods,
    &descriptor_table_request_2frequest_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* RequestData::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 17, 14, 55, 2> RequestData::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    21, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4292870624,  // skipmap
    offsetof(decltype(_table_), field_entries),
    17,  // num_field_entries
    14,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::request::RequestData>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .request.RequestType type = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RequestData, _impl_.type_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(RequestData, _impl_.type_)}},
    // string cmd = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(RequestData, _impl_.cmd_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    // uint64 id = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(RequestData, _impl_.id_), 63>(),
     {40, 63, 0, PROTOBUF_FIELD_OFFSET(RequestData, _impl_.id_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // .request.RequestType type = 1;
    {PROTOBUF_FIELD_OFFSET(RequestData, _impl_.type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // string cmd = 2;
    {PROTOBUF_FIELD_OFFSET(RequestData, _impl_.cmd_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // map<string, string> extra = 3;
    {PROTOBUF_FIELD_OFFSET(RequestData, _impl_.extra_), 0, 12,
    (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
    // map<string, string> ret = 4;
    {PROTOBUF_FIELD_OFFSET(RequestData, _impl_.ret_), 0, 13,
    (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
    // uint64 id = 5;
    {PROTOBUF_FIELD_OFFSET(RequestData, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // .hqmarket.market.v1.AuthRequest auth_request = 10;
    {PROTOBUF_FIELD_OFFSET(RequestData, _impl_.payload_.auth_request_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .hqmarket.market.v1.SubscribeRequest subscribe_request = 11;
    {PROTOBUF_FIELD_OFFSET(RequestData, _impl_.payload_.subscribe_request_), _Internal::kOneofCaseOffset + 0, 1,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .hqmarket.market.v1.UnsubscribeRequest unsubscribe_request = 12;
    {PROTOBUF_FIELD_OFFSET(RequestData, _impl_.payload_.unsubscribe_request_), _Internal::kOneofCaseOffset + 0, 2,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .hqmarket.market.v1.SubscriptionAck subscription_ack = 13;
    {PROTOBUF_FIELD_OFFSET(RequestData, _impl_.payload_.subscription_ack_), _Internal::kOneofCaseOffset + 0, 3,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .hqmarket.market.v1.QuoteData quote = 14;
    {PROTOBUF_FIELD_OFFSET(RequestData, _impl_.payload_.quote_), _Internal::kOneofCaseOffset + 0, 4,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .hqmarket.market.v1.DepthData depth = 15;
    {PROTOBUF_FIELD_OFFSET(RequestData, _impl_.payload_.depth_), _Internal::kOneofCaseOffset + 0, 5,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .hqmarket.market.v1.TradeData trade = 16;
    {PROTOBUF_FIELD_OFFSET(RequestData, _impl_.payload_.trade_), _Internal::kOneofCaseOffset + 0, 6,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .hqmarket.market.v1.BarData bar = 17;
    {PROTOBUF_FIELD_OFFSET(RequestData, _impl_.payload_.bar_), _Internal::kOneofCaseOffset + 0, 7,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .hqmarket.market.v1.MarketStatusData market_status = 18;
    {PROTOBUF_FIELD_OFFSET(RequestData, _impl_.payload_.market_status_), _Internal::kOneofCaseOffset + 0, 8,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .hqmarket.market.v1.ProviderStatusData provider_status = 19;
    {PROTOBUF_FIELD_OFFSET(RequestData, _impl_.payload_.provider_status_), _Internal::kOneofCaseOffset + 0, 9,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .hqmarket.market.v1.QueryRequest query_request = 20;
    {PROTOBUF_FIELD_OFFSET(RequestData, _impl_.payload_.query_request_), _Internal::kOneofCaseOffset + 0, 10,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .hqmarket.market.v1.QueryResponse query_response = 21;
    {PROTOBUF_FIELD_OFFSET(RequestData, _impl_.payload_.query_response_), _Internal::kOneofCaseOffset + 0, 11,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::hqmarket::market::v1::AuthRequest>()},
    {::_pbi::TcParser::GetTable<::hqmarket::market::v1::SubscribeRequest>()},
    {::_pbi::TcParser::GetTable<::hqmarket::market::v1::UnsubscribeRequest>()},
    {::_pbi::TcParser::GetTable<::hqmarket::market::v1::SubscriptionAck>()},
    {::_pbi::TcParser::GetTable<::hqmarket::market::v1::QuoteData>()},
    {::_pbi::TcParser::GetTable<::hqmarket::market::v1::DepthData>()},
    {::_pbi::TcParser::GetTable<::hqmarket::market::v1::TradeData>()},
    {::_pbi::TcParser::GetTable<::hqmarket::market::v1::BarData>()},
    {::_pbi::TcParser::GetTable<::hqmarket::market::v1::MarketStatusData>()},
    {::_pbi::TcParser::GetTable<::hqmarket::market::v1::ProviderStatusData>()},
    {::_pbi::TcParser::GetTable<::hqmarket::market::v1::QueryRequest>()},
    {::_pbi::TcParser::GetTable<::hqmarket::market::v1::QueryResponse>()},
    {::_pbi::TcParser::GetMapAuxInfo<
        decltype(RequestData()._impl_.extra_)>(
        1, 0, 0, 9,
        9)},
    {::_pbi::TcParser::GetMapAuxInfo<
        decltype(RequestData()._impl_.ret_)>(
        1, 0, 0, 9,
        9)},
  }}, {{
    "\23\0\3\5\3\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
    "request.RequestData"
    "cmd"
    "extra"
    "ret"
  }},
};

PROTOBUF_NOINLINE void RequestData::Clear() {
// @@protoc_insertion_point(message_clear_start:request.RequestData)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.extra_.Clear();
  _impl_.ret_.Clear();
  _impl_.cmd_.ClearToEmpty();
  ::memset(&_impl_.id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.type_) -
      reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.type_));
  clear_payload();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* RequestData::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const RequestData& this_ = static_cast<const RequestData&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* RequestData::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const RequestData& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:request.RequestData)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // .request.RequestType type = 1;
          if (this_._internal_type() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                1, this_._internal_type(), target);
          }

          // string cmd = 2;
          if (!this_._internal_cmd().empty()) {
            const std::string& _s = this_._internal_cmd();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "request.RequestData.cmd");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // map<string, string> extra = 3;
          if (!this_._internal_extra().empty()) {
            using MapType = ::google::protobuf::Map<std::string, std::string>;
            using WireHelper = _pbi::MapEntryFuncs<std::string, std::string,
                                           _pbi::WireFormatLite::TYPE_STRING,
                                           _pbi::WireFormatLite::TYPE_STRING>;
            const auto& field = this_._internal_extra();

            if (stream->IsSerializationDeterministic() && field.size() > 1) {
              for (const auto& entry : ::google::protobuf::internal::MapSorterPtr<MapType>(field)) {
                target = WireHelper::InternalSerialize(
                    3, entry.first, entry.second, target, stream);
                ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                    entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "request.RequestData.extra");
                ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                    entry.second.data(), static_cast<int>(entry.second.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "request.RequestData.extra");
              }
            } else {
              for (const auto& entry : field) {
                target = WireHelper::InternalSerialize(
                    3, entry.first, entry.second, target, stream);
                ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                    entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "request.RequestData.extra");
                ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                    entry.second.data(), static_cast<int>(entry.second.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "request.RequestData.extra");
              }
            }
          }

          // map<string, string> ret = 4;
          if (!this_._internal_ret().empty()) {
            using MapType = ::google::protobuf::Map<std::string, std::string>;
            using WireHelper = _pbi::MapEntryFuncs<std::string, std::string,
                                           _pbi::WireFormatLite::TYPE_STRING,
                                           _pbi::WireFormatLite::TYPE_STRING>;
            const auto& field = this_._internal_ret();

            if (stream->IsSerializationDeterministic() && field.size() > 1) {
              for (const auto& entry : ::google::protobuf::internal::MapSorterPtr<MapType>(field)) {
                target = WireHelper::InternalSerialize(
                    4, entry.first, entry.second, target, stream);
                ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                    entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "request.RequestData.ret");
                ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                    entry.second.data(), static_cast<int>(entry.second.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "request.RequestData.ret");
              }
            } else {
              for (const auto& entry : field) {
                target = WireHelper::InternalSerialize(
                    4, entry.first, entry.second, target, stream);
                ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                    entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "request.RequestData.ret");
                ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                    entry.second.data(), static_cast<int>(entry.second.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "request.RequestData.ret");
              }
            }
          }

          // uint64 id = 5;
          if (this_._internal_id() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                5, this_._internal_id(), target);
          }

          switch (this_.payload_case()) {
            case kAuthRequest: {
              target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                  10, *this_._impl_.payload_.auth_request_, this_._impl_.payload_.auth_request_->GetCachedSize(), target,
                  stream);
              break;
            }
            case kSubscribeRequest: {
              target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                  11, *this_._impl_.payload_.subscribe_request_, this_._impl_.payload_.subscribe_request_->GetCachedSize(), target,
                  stream);
              break;
            }
            case kUnsubscribeRequest: {
              target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                  12, *this_._impl_.payload_.unsubscribe_request_, this_._impl_.payload_.unsubscribe_request_->GetCachedSize(), target,
                  stream);
              break;
            }
            case kSubscriptionAck: {
              target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                  13, *this_._impl_.payload_.subscription_ack_, this_._impl_.payload_.subscription_ack_->GetCachedSize(), target,
                  stream);
              break;
            }
            case kQuote: {
              target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                  14, *this_._impl_.payload_.quote_, this_._impl_.payload_.quote_->GetCachedSize(), target,
                  stream);
              break;
            }
            case kDepth: {
              target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                  15, *this_._impl_.payload_.depth_, this_._impl_.payload_.depth_->GetCachedSize(), target,
                  stream);
              break;
            }
            case kTrade: {
              target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                  16, *this_._impl_.payload_.trade_, this_._impl_.payload_.trade_->GetCachedSize(), target,
                  stream);
              break;
            }
            case kBar: {
              target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                  17, *this_._impl_.payload_.bar_, this_._impl_.payload_.bar_->GetCachedSize(), target,
                  stream);
              break;
            }
            case kMarketStatus: {
              target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                  18, *this_._impl_.payload_.market_status_, this_._impl_.payload_.market_status_->GetCachedSize(), target,
                  stream);
              break;
            }
            case kProviderStatus: {
              target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                  19, *this_._impl_.payload_.provider_status_, this_._impl_.payload_.provider_status_->GetCachedSize(), target,
                  stream);
              break;
            }
            case kQueryRequest: {
              target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                  20, *this_._impl_.payload_.query_request_, this_._impl_.payload_.query_request_->GetCachedSize(), target,
                  stream);
              break;
            }
            case kQueryResponse: {
              target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                  21, *this_._impl_.payload_.query_response_, this_._impl_.payload_.query_response_->GetCachedSize(), target,
                  stream);
              break;
            }
            default:
              break;
          }
          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:request.RequestData)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t RequestData::ByteSizeLong(const MessageLite& base) {
          const RequestData& this_ = static_cast<const RequestData&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t RequestData::ByteSizeLong() const {
          const RequestData& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:request.RequestData)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // map<string, string> extra = 3;
            {
              total_size +=
                  1 * ::google::protobuf::internal::FromIntSize(this_._internal_extra_size());
              for (const auto& entry : this_._internal_extra()) {
                total_size += _pbi::MapEntryFuncs<std::string, std::string,
                                               _pbi::WireFormatLite::TYPE_STRING,
                                               _pbi::WireFormatLite::TYPE_STRING>::ByteSizeLong(entry.first, entry.second);
              }
            }
            // map<string, string> ret = 4;
            {
              total_size +=
                  1 * ::google::protobuf::internal::FromIntSize(this_._internal_ret_size());
              for (const auto& entry : this_._internal_ret()) {
                total_size += _pbi::MapEntryFuncs<std::string, std::string,
                                               _pbi::WireFormatLite::TYPE_STRING,
                                               _pbi::WireFormatLite::TYPE_STRING>::ByteSizeLong(entry.first, entry.second);
              }
            }
          }
           {
            // string cmd = 2;
            if (!this_._internal_cmd().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_cmd());
            }
            // uint64 id = 5;
            if (this_._internal_id() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_id());
            }
            // .request.RequestType type = 1;
            if (this_._internal_type() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_type());
            }
          }
          switch (this_.payload_case()) {
            // .hqmarket.market.v1.AuthRequest auth_request = 10;
            case kAuthRequest: {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.auth_request_);
              break;
            }
            // .hqmarket.market.v1.SubscribeRequest subscribe_request = 11;
            case kSubscribeRequest: {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.subscribe_request_);
              break;
            }
            // .hqmarket.market.v1.UnsubscribeRequest unsubscribe_request = 12;
            case kUnsubscribeRequest: {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.unsubscribe_request_);
              break;
            }
            // .hqmarket.market.v1.SubscriptionAck subscription_ack = 13;
            case kSubscriptionAck: {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.subscription_ack_);
              break;
            }
            // .hqmarket.market.v1.QuoteData quote = 14;
            case kQuote: {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.quote_);
              break;
            }
            // .hqmarket.market.v1.DepthData depth = 15;
            case kDepth: {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.depth_);
              break;
            }
            // .hqmarket.market.v1.TradeData trade = 16;
            case kTrade: {
              total_size += 2 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.trade_);
              break;
            }
            // .hqmarket.market.v1.BarData bar = 17;
            case kBar: {
              total_size += 2 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.bar_);
              break;
            }
            // .hqmarket.market.v1.MarketStatusData market_status = 18;
            case kMarketStatus: {
              total_size += 2 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.market_status_);
              break;
            }
            // .hqmarket.market.v1.ProviderStatusData provider_status = 19;
            case kProviderStatus: {
              total_size += 2 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.provider_status_);
              break;
            }
            // .hqmarket.market.v1.QueryRequest query_request = 20;
            case kQueryRequest: {
              total_size += 2 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.query_request_);
              break;
            }
            // .hqmarket.market.v1.QueryResponse query_response = 21;
            case kQueryResponse: {
              total_size += 2 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.query_response_);
              break;
            }
            case PAYLOAD_NOT_SET: {
              break;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void RequestData::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<RequestData*>(&to_msg);
  auto& from = static_cast<const RequestData&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:request.RequestData)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.extra_.MergeFrom(from._impl_.extra_);
  _this->_impl_.ret_.MergeFrom(from._impl_.ret_);
  if (!from._internal_cmd().empty()) {
    _this->_internal_set_cmd(from._internal_cmd());
  }
  if (from._internal_id() != 0) {
    _this->_impl_.id_ = from._impl_.id_;
  }
  if (from._internal_type() != 0) {
    _this->_impl_.type_ = from._impl_.type_;
  }
  if (const uint32_t oneof_from_case = from._impl_._oneof_case_[0]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_payload();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kAuthRequest: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.auth_request_ =
              ::google::protobuf::Message::CopyConstruct<::hqmarket::market::v1::AuthRequest>(arena, *from._impl_.payload_.auth_request_);
        } else {
          _this->_impl_.payload_.auth_request_->MergeFrom(from._internal_auth_request());
        }
        break;
      }
      case kSubscribeRequest: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.subscribe_request_ =
              ::google::protobuf::Message::CopyConstruct<::hqmarket::market::v1::SubscribeRequest>(arena, *from._impl_.payload_.subscribe_request_);
        } else {
          _this->_impl_.payload_.subscribe_request_->MergeFrom(from._internal_subscribe_request());
        }
        break;
      }
      case kUnsubscribeRequest: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.unsubscribe_request_ =
              ::google::protobuf::Message::CopyConstruct<::hqmarket::market::v1::UnsubscribeRequest>(arena, *from._impl_.payload_.unsubscribe_request_);
        } else {
          _this->_impl_.payload_.unsubscribe_request_->MergeFrom(from._internal_unsubscribe_request());
        }
        break;
      }
      case kSubscriptionAck: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.subscription_ack_ =
              ::google::protobuf::Message::CopyConstruct<::hqmarket::market::v1::SubscriptionAck>(arena, *from._impl_.payload_.subscription_ack_);
        } else {
          _this->_impl_.payload_.subscription_ack_->MergeFrom(from._internal_subscription_ack());
        }
        break;
      }
      case kQuote: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.quote_ =
              ::google::protobuf::Message::CopyConstruct<::hqmarket::market::v1::QuoteData>(arena, *from._impl_.payload_.quote_);
        } else {
          _this->_impl_.payload_.quote_->MergeFrom(from._internal_quote());
        }
        break;
      }
      case kDepth: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.depth_ =
              ::google::protobuf::Message::CopyConstruct<::hqmarket::market::v1::DepthData>(arena, *from._impl_.payload_.depth_);
        } else {
          _this->_impl_.payload_.depth_->MergeFrom(from._internal_depth());
        }
        break;
      }
      case kTrade: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.trade_ =
              ::google::protobuf::Message::CopyConstruct<::hqmarket::market::v1::TradeData>(arena, *from._impl_.payload_.trade_);
        } else {
          _this->_impl_.payload_.trade_->MergeFrom(from._internal_trade());
        }
        break;
      }
      case kBar: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.bar_ =
              ::google::protobuf::Message::CopyConstruct<::hqmarket::market::v1::BarData>(arena, *from._impl_.payload_.bar_);
        } else {
          _this->_impl_.payload_.bar_->MergeFrom(from._internal_bar());
        }
        break;
      }
      case kMarketStatus: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.market_status_ =
              ::google::protobuf::Message::CopyConstruct<::hqmarket::market::v1::MarketStatusData>(arena, *from._impl_.payload_.market_status_);
        } else {
          _this->_impl_.payload_.market_status_->MergeFrom(from._internal_market_status());
        }
        break;
      }
      case kProviderStatus: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.provider_status_ =
              ::google::protobuf::Message::CopyConstruct<::hqmarket::market::v1::ProviderStatusData>(arena, *from._impl_.payload_.provider_status_);
        } else {
          _this->_impl_.payload_.provider_status_->MergeFrom(from._internal_provider_status());
        }
        break;
      }
      case kQueryRequest: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.query_request_ =
              ::google::protobuf::Message::CopyConstruct<::hqmarket::market::v1::QueryRequest>(arena, *from._impl_.payload_.query_request_);
        } else {
          _this->_impl_.payload_.query_request_->MergeFrom(from._internal_query_request());
        }
        break;
      }
      case kQueryResponse: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.query_response_ =
              ::google::protobuf::Message::CopyConstruct<::hqmarket::market::v1::QueryResponse>(arena, *from._impl_.payload_.query_response_);
        } else {
          _this->_impl_.payload_.query_response_->MergeFrom(from._internal_query_response());
        }
        break;
      }
      case PAYLOAD_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RequestData::CopyFrom(const RequestData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:request.RequestData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RequestData::InternalSwap(RequestData* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.extra_.InternalSwap(&other->_impl_.extra_);
  _impl_.ret_.InternalSwap(&other->_impl_.ret_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.cmd_, &other->_impl_.cmd_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RequestData, _impl_.type_)
      + sizeof(RequestData::_impl_.type_)
      - PROTOBUF_FIELD_OFFSET(RequestData, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
  swap(_impl_.payload_, other->_impl_.payload_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata RequestData::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace request
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_request_2frequest_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
