// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: request/request.proto
// Protobuf C++ Version: 5.29.3

#ifndef request_2frequest_2eproto_2epb_2eh
#define request_2frequest_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/map.h"  // IWYU pragma: export
#include "google/protobuf/map_entry.h"
#include "google/protobuf/map_field_inl.h"
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
#include "hqmarket/v1/market.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_request_2frequest_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_request_2frequest_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_request_2frequest_2eproto;
namespace request {
class RequestData;
struct RequestDataDefaultTypeInternal;
extern RequestDataDefaultTypeInternal _RequestData_default_instance_;
class RequestData_ExtraEntry_DoNotUse;
struct RequestData_ExtraEntry_DoNotUseDefaultTypeInternal;
extern RequestData_ExtraEntry_DoNotUseDefaultTypeInternal _RequestData_ExtraEntry_DoNotUse_default_instance_;
class RequestData_RetEntry_DoNotUse;
struct RequestData_RetEntry_DoNotUseDefaultTypeInternal;
extern RequestData_RetEntry_DoNotUseDefaultTypeInternal _RequestData_RetEntry_DoNotUse_default_instance_;
}  // namespace request
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace request {
enum RequestType : int {
  UNKNOWN = 0,
  QUERY_AUTH = 1,
  QUERY_USERINFO = 2,
  UPDATE_AUTH = 3,
  UPDAT_PRODUCT = 4,
  HQMARKET = 5,
  HEARTBEAT = 6,
  RequestType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  RequestType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool RequestType_IsValid(int value);
extern const uint32_t RequestType_internal_data_[];
constexpr RequestType RequestType_MIN = static_cast<RequestType>(0);
constexpr RequestType RequestType_MAX = static_cast<RequestType>(6);
constexpr int RequestType_ARRAYSIZE = 6 + 1;
const ::google::protobuf::EnumDescriptor*
RequestType_descriptor();
template <typename T>
const std::string& RequestType_Name(T value) {
  static_assert(std::is_same<T, RequestType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to RequestType_Name().");
  return RequestType_Name(static_cast<RequestType>(value));
}
template <>
inline const std::string& RequestType_Name(RequestType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<RequestType_descriptor,
                                                 0, 6>(
      static_cast<int>(value));
}
inline bool RequestType_Parse(absl::string_view name, RequestType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<RequestType>(
      RequestType_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class RequestData_RetEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<
          std::string, std::string,
          ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
          ::google::protobuf::internal::WireFormatLite::TYPE_STRING> {
 public:
  using SuperType = ::google::protobuf::internal::MapEntry<
      std::string, std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING>;
  RequestData_RetEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RequestData_RetEntry_DoNotUse(
      ::google::protobuf::internal::ConstantInitialized);
  explicit RequestData_RetEntry_DoNotUse(::google::protobuf::Arena* arena);
  static const RequestData_RetEntry_DoNotUse* internal_default_instance() {
    return reinterpret_cast<const RequestData_RetEntry_DoNotUse*>(
        &_RequestData_RetEntry_DoNotUse_default_instance_);
  }


 private:
  friend class ::google::protobuf::MessageLite;
  friend struct ::TableStruct_request_2frequest_2eproto;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      45, 2>
      _table_;

  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;
};
// -------------------------------------------------------------------

class RequestData_ExtraEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<
          std::string, std::string,
          ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
          ::google::protobuf::internal::WireFormatLite::TYPE_STRING> {
 public:
  using SuperType = ::google::protobuf::internal::MapEntry<
      std::string, std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING>;
  RequestData_ExtraEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RequestData_ExtraEntry_DoNotUse(
      ::google::protobuf::internal::ConstantInitialized);
  explicit RequestData_ExtraEntry_DoNotUse(::google::protobuf::Arena* arena);
  static const RequestData_ExtraEntry_DoNotUse* internal_default_instance() {
    return reinterpret_cast<const RequestData_ExtraEntry_DoNotUse*>(
        &_RequestData_ExtraEntry_DoNotUse_default_instance_);
  }


 private:
  friend class ::google::protobuf::MessageLite;
  friend struct ::TableStruct_request_2frequest_2eproto;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      47, 2>
      _table_;

  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;
};
// -------------------------------------------------------------------

class RequestData final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:request.RequestData) */ {
 public:
  inline RequestData() : RequestData(nullptr) {}
  ~RequestData() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RequestData* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RequestData));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RequestData(
      ::google::protobuf::internal::ConstantInitialized);

  inline RequestData(const RequestData& from) : RequestData(nullptr, from) {}
  inline RequestData(RequestData&& from) noexcept
      : RequestData(nullptr, std::move(from)) {}
  inline RequestData& operator=(const RequestData& from) {
    CopyFrom(from);
    return *this;
  }
  inline RequestData& operator=(RequestData&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RequestData& default_instance() {
    return *internal_default_instance();
  }
  enum PayloadCase {
    kAuthRequest = 10,
    kSubscribeRequest = 11,
    kUnsubscribeRequest = 12,
    kSubscriptionAck = 13,
    kQuote = 14,
    kDepth = 15,
    kTrade = 16,
    kBar = 17,
    kMarketStatus = 18,
    kProviderStatus = 19,
    kQueryRequest = 20,
    kQueryResponse = 21,
    PAYLOAD_NOT_SET = 0,
  };
  static inline const RequestData* internal_default_instance() {
    return reinterpret_cast<const RequestData*>(
        &_RequestData_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(RequestData& a, RequestData& b) { a.Swap(&b); }
  inline void Swap(RequestData* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RequestData* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RequestData* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RequestData>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RequestData& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RequestData& from) { RequestData::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RequestData* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "request.RequestData"; }

 protected:
  explicit RequestData(::google::protobuf::Arena* arena);
  RequestData(::google::protobuf::Arena* arena, const RequestData& from);
  RequestData(::google::protobuf::Arena* arena, RequestData&& from) noexcept
      : RequestData(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kExtraFieldNumber = 3,
    kRetFieldNumber = 4,
    kCmdFieldNumber = 2,
    kIdFieldNumber = 5,
    kTypeFieldNumber = 1,
    kAuthRequestFieldNumber = 10,
    kSubscribeRequestFieldNumber = 11,
    kUnsubscribeRequestFieldNumber = 12,
    kSubscriptionAckFieldNumber = 13,
    kQuoteFieldNumber = 14,
    kDepthFieldNumber = 15,
    kTradeFieldNumber = 16,
    kBarFieldNumber = 17,
    kMarketStatusFieldNumber = 18,
    kProviderStatusFieldNumber = 19,
    kQueryRequestFieldNumber = 20,
    kQueryResponseFieldNumber = 21,
  };
  // map<string, string> extra = 3;
  int extra_size() const;
  private:
  int _internal_extra_size() const;

  public:
  void clear_extra() ;
  const ::google::protobuf::Map<std::string, std::string>& extra() const;
  ::google::protobuf::Map<std::string, std::string>* mutable_extra();

  private:
  const ::google::protobuf::Map<std::string, std::string>& _internal_extra() const;
  ::google::protobuf::Map<std::string, std::string>* _internal_mutable_extra();

  public:
  // map<string, string> ret = 4;
  int ret_size() const;
  private:
  int _internal_ret_size() const;

  public:
  void clear_ret() ;
  const ::google::protobuf::Map<std::string, std::string>& ret() const;
  ::google::protobuf::Map<std::string, std::string>* mutable_ret();

  private:
  const ::google::protobuf::Map<std::string, std::string>& _internal_ret() const;
  ::google::protobuf::Map<std::string, std::string>* _internal_mutable_ret();

  public:
  // string cmd = 2;
  void clear_cmd() ;
  const std::string& cmd() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_cmd(Arg_&& arg, Args_... args);
  std::string* mutable_cmd();
  PROTOBUF_NODISCARD std::string* release_cmd();
  void set_allocated_cmd(std::string* value);

  private:
  const std::string& _internal_cmd() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_cmd(
      const std::string& value);
  std::string* _internal_mutable_cmd();

  public:
  // uint64 id = 5;
  void clear_id() ;
  ::uint64_t id() const;
  void set_id(::uint64_t value);

  private:
  ::uint64_t _internal_id() const;
  void _internal_set_id(::uint64_t value);

  public:
  // .request.RequestType type = 1;
  void clear_type() ;
  ::request::RequestType type() const;
  void set_type(::request::RequestType value);

  private:
  ::request::RequestType _internal_type() const;
  void _internal_set_type(::request::RequestType value);

  public:
  // .hqmarket.market.v1.AuthRequest auth_request = 10;
  bool has_auth_request() const;
  private:
  bool _internal_has_auth_request() const;

  public:
  void clear_auth_request() ;
  const ::hqmarket::market::v1::AuthRequest& auth_request() const;
  PROTOBUF_NODISCARD ::hqmarket::market::v1::AuthRequest* release_auth_request();
  ::hqmarket::market::v1::AuthRequest* mutable_auth_request();
  void set_allocated_auth_request(::hqmarket::market::v1::AuthRequest* value);
  void unsafe_arena_set_allocated_auth_request(::hqmarket::market::v1::AuthRequest* value);
  ::hqmarket::market::v1::AuthRequest* unsafe_arena_release_auth_request();

  private:
  const ::hqmarket::market::v1::AuthRequest& _internal_auth_request() const;
  ::hqmarket::market::v1::AuthRequest* _internal_mutable_auth_request();

  public:
  // .hqmarket.market.v1.SubscribeRequest subscribe_request = 11;
  bool has_subscribe_request() const;
  private:
  bool _internal_has_subscribe_request() const;

  public:
  void clear_subscribe_request() ;
  const ::hqmarket::market::v1::SubscribeRequest& subscribe_request() const;
  PROTOBUF_NODISCARD ::hqmarket::market::v1::SubscribeRequest* release_subscribe_request();
  ::hqmarket::market::v1::SubscribeRequest* mutable_subscribe_request();
  void set_allocated_subscribe_request(::hqmarket::market::v1::SubscribeRequest* value);
  void unsafe_arena_set_allocated_subscribe_request(::hqmarket::market::v1::SubscribeRequest* value);
  ::hqmarket::market::v1::SubscribeRequest* unsafe_arena_release_subscribe_request();

  private:
  const ::hqmarket::market::v1::SubscribeRequest& _internal_subscribe_request() const;
  ::hqmarket::market::v1::SubscribeRequest* _internal_mutable_subscribe_request();

  public:
  // .hqmarket.market.v1.UnsubscribeRequest unsubscribe_request = 12;
  bool has_unsubscribe_request() const;
  private:
  bool _internal_has_unsubscribe_request() const;

  public:
  void clear_unsubscribe_request() ;
  const ::hqmarket::market::v1::UnsubscribeRequest& unsubscribe_request() const;
  PROTOBUF_NODISCARD ::hqmarket::market::v1::UnsubscribeRequest* release_unsubscribe_request();
  ::hqmarket::market::v1::UnsubscribeRequest* mutable_unsubscribe_request();
  void set_allocated_unsubscribe_request(::hqmarket::market::v1::UnsubscribeRequest* value);
  void unsafe_arena_set_allocated_unsubscribe_request(::hqmarket::market::v1::UnsubscribeRequest* value);
  ::hqmarket::market::v1::UnsubscribeRequest* unsafe_arena_release_unsubscribe_request();

  private:
  const ::hqmarket::market::v1::UnsubscribeRequest& _internal_unsubscribe_request() const;
  ::hqmarket::market::v1::UnsubscribeRequest* _internal_mutable_unsubscribe_request();

  public:
  // .hqmarket.market.v1.SubscriptionAck subscription_ack = 13;
  bool has_subscription_ack() const;
  private:
  bool _internal_has_subscription_ack() const;

  public:
  void clear_subscription_ack() ;
  const ::hqmarket::market::v1::SubscriptionAck& subscription_ack() const;
  PROTOBUF_NODISCARD ::hqmarket::market::v1::SubscriptionAck* release_subscription_ack();
  ::hqmarket::market::v1::SubscriptionAck* mutable_subscription_ack();
  void set_allocated_subscription_ack(::hqmarket::market::v1::SubscriptionAck* value);
  void unsafe_arena_set_allocated_subscription_ack(::hqmarket::market::v1::SubscriptionAck* value);
  ::hqmarket::market::v1::SubscriptionAck* unsafe_arena_release_subscription_ack();

  private:
  const ::hqmarket::market::v1::SubscriptionAck& _internal_subscription_ack() const;
  ::hqmarket::market::v1::SubscriptionAck* _internal_mutable_subscription_ack();

  public:
  // .hqmarket.market.v1.QuoteData quote = 14;
  bool has_quote() const;
  private:
  bool _internal_has_quote() const;

  public:
  void clear_quote() ;
  const ::hqmarket::market::v1::QuoteData& quote() const;
  PROTOBUF_NODISCARD ::hqmarket::market::v1::QuoteData* release_quote();
  ::hqmarket::market::v1::QuoteData* mutable_quote();
  void set_allocated_quote(::hqmarket::market::v1::QuoteData* value);
  void unsafe_arena_set_allocated_quote(::hqmarket::market::v1::QuoteData* value);
  ::hqmarket::market::v1::QuoteData* unsafe_arena_release_quote();

  private:
  const ::hqmarket::market::v1::QuoteData& _internal_quote() const;
  ::hqmarket::market::v1::QuoteData* _internal_mutable_quote();

  public:
  // .hqmarket.market.v1.DepthData depth = 15;
  bool has_depth() const;
  private:
  bool _internal_has_depth() const;

  public:
  void clear_depth() ;
  const ::hqmarket::market::v1::DepthData& depth() const;
  PROTOBUF_NODISCARD ::hqmarket::market::v1::DepthData* release_depth();
  ::hqmarket::market::v1::DepthData* mutable_depth();
  void set_allocated_depth(::hqmarket::market::v1::DepthData* value);
  void unsafe_arena_set_allocated_depth(::hqmarket::market::v1::DepthData* value);
  ::hqmarket::market::v1::DepthData* unsafe_arena_release_depth();

  private:
  const ::hqmarket::market::v1::DepthData& _internal_depth() const;
  ::hqmarket::market::v1::DepthData* _internal_mutable_depth();

  public:
  // .hqmarket.market.v1.TradeData trade = 16;
  bool has_trade() const;
  private:
  bool _internal_has_trade() const;

  public:
  void clear_trade() ;
  const ::hqmarket::market::v1::TradeData& trade() const;
  PROTOBUF_NODISCARD ::hqmarket::market::v1::TradeData* release_trade();
  ::hqmarket::market::v1::TradeData* mutable_trade();
  void set_allocated_trade(::hqmarket::market::v1::TradeData* value);
  void unsafe_arena_set_allocated_trade(::hqmarket::market::v1::TradeData* value);
  ::hqmarket::market::v1::TradeData* unsafe_arena_release_trade();

  private:
  const ::hqmarket::market::v1::TradeData& _internal_trade() const;
  ::hqmarket::market::v1::TradeData* _internal_mutable_trade();

  public:
  // .hqmarket.market.v1.BarData bar = 17;
  bool has_bar() const;
  private:
  bool _internal_has_bar() const;

  public:
  void clear_bar() ;
  const ::hqmarket::market::v1::BarData& bar() const;
  PROTOBUF_NODISCARD ::hqmarket::market::v1::BarData* release_bar();
  ::hqmarket::market::v1::BarData* mutable_bar();
  void set_allocated_bar(::hqmarket::market::v1::BarData* value);
  void unsafe_arena_set_allocated_bar(::hqmarket::market::v1::BarData* value);
  ::hqmarket::market::v1::BarData* unsafe_arena_release_bar();

  private:
  const ::hqmarket::market::v1::BarData& _internal_bar() const;
  ::hqmarket::market::v1::BarData* _internal_mutable_bar();

  public:
  // .hqmarket.market.v1.MarketStatusData market_status = 18;
  bool has_market_status() const;
  private:
  bool _internal_has_market_status() const;

  public:
  void clear_market_status() ;
  const ::hqmarket::market::v1::MarketStatusData& market_status() const;
  PROTOBUF_NODISCARD ::hqmarket::market::v1::MarketStatusData* release_market_status();
  ::hqmarket::market::v1::MarketStatusData* mutable_market_status();
  void set_allocated_market_status(::hqmarket::market::v1::MarketStatusData* value);
  void unsafe_arena_set_allocated_market_status(::hqmarket::market::v1::MarketStatusData* value);
  ::hqmarket::market::v1::MarketStatusData* unsafe_arena_release_market_status();

  private:
  const ::hqmarket::market::v1::MarketStatusData& _internal_market_status() const;
  ::hqmarket::market::v1::MarketStatusData* _internal_mutable_market_status();

  public:
  // .hqmarket.market.v1.ProviderStatusData provider_status = 19;
  bool has_provider_status() const;
  private:
  bool _internal_has_provider_status() const;

  public:
  void clear_provider_status() ;
  const ::hqmarket::market::v1::ProviderStatusData& provider_status() const;
  PROTOBUF_NODISCARD ::hqmarket::market::v1::ProviderStatusData* release_provider_status();
  ::hqmarket::market::v1::ProviderStatusData* mutable_provider_status();
  void set_allocated_provider_status(::hqmarket::market::v1::ProviderStatusData* value);
  void unsafe_arena_set_allocated_provider_status(::hqmarket::market::v1::ProviderStatusData* value);
  ::hqmarket::market::v1::ProviderStatusData* unsafe_arena_release_provider_status();

  private:
  const ::hqmarket::market::v1::ProviderStatusData& _internal_provider_status() const;
  ::hqmarket::market::v1::ProviderStatusData* _internal_mutable_provider_status();

  public:
  // .hqmarket.market.v1.QueryRequest query_request = 20;
  bool has_query_request() const;
  private:
  bool _internal_has_query_request() const;

  public:
  void clear_query_request() ;
  const ::hqmarket::market::v1::QueryRequest& query_request() const;
  PROTOBUF_NODISCARD ::hqmarket::market::v1::QueryRequest* release_query_request();
  ::hqmarket::market::v1::QueryRequest* mutable_query_request();
  void set_allocated_query_request(::hqmarket::market::v1::QueryRequest* value);
  void unsafe_arena_set_allocated_query_request(::hqmarket::market::v1::QueryRequest* value);
  ::hqmarket::market::v1::QueryRequest* unsafe_arena_release_query_request();

  private:
  const ::hqmarket::market::v1::QueryRequest& _internal_query_request() const;
  ::hqmarket::market::v1::QueryRequest* _internal_mutable_query_request();

  public:
  // .hqmarket.market.v1.QueryResponse query_response = 21;
  bool has_query_response() const;
  private:
  bool _internal_has_query_response() const;

  public:
  void clear_query_response() ;
  const ::hqmarket::market::v1::QueryResponse& query_response() const;
  PROTOBUF_NODISCARD ::hqmarket::market::v1::QueryResponse* release_query_response();
  ::hqmarket::market::v1::QueryResponse* mutable_query_response();
  void set_allocated_query_response(::hqmarket::market::v1::QueryResponse* value);
  void unsafe_arena_set_allocated_query_response(::hqmarket::market::v1::QueryResponse* value);
  ::hqmarket::market::v1::QueryResponse* unsafe_arena_release_query_response();

  private:
  const ::hqmarket::market::v1::QueryResponse& _internal_query_response() const;
  ::hqmarket::market::v1::QueryResponse* _internal_mutable_query_response();

  public:
  void clear_payload();
  PayloadCase payload_case() const;
  // @@protoc_insertion_point(class_scope:request.RequestData)
 private:
  class _Internal;
  void set_has_auth_request();
  void set_has_subscribe_request();
  void set_has_unsubscribe_request();
  void set_has_subscription_ack();
  void set_has_quote();
  void set_has_depth();
  void set_has_trade();
  void set_has_bar();
  void set_has_market_status();
  void set_has_provider_status();
  void set_has_query_request();
  void set_has_query_response();
  inline bool has_payload() const;
  inline void clear_has_payload();
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 17, 14,
      55, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const RequestData& from_msg);
    ::google::protobuf::internal::MapField<RequestData_ExtraEntry_DoNotUse, std::string, std::string,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING>
        extra_;
    ::google::protobuf::internal::MapField<RequestData_RetEntry_DoNotUse, std::string, std::string,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING>
        ret_;
    ::google::protobuf::internal::ArenaStringPtr cmd_;
    ::uint64_t id_;
    int type_;
    union PayloadUnion {
      constexpr PayloadUnion() : _constinit_{} {}
      ::google::protobuf::internal::ConstantInitialized _constinit_;
      ::hqmarket::market::v1::AuthRequest* auth_request_;
      ::hqmarket::market::v1::SubscribeRequest* subscribe_request_;
      ::hqmarket::market::v1::UnsubscribeRequest* unsubscribe_request_;
      ::hqmarket::market::v1::SubscriptionAck* subscription_ack_;
      ::hqmarket::market::v1::QuoteData* quote_;
      ::hqmarket::market::v1::DepthData* depth_;
      ::hqmarket::market::v1::TradeData* trade_;
      ::hqmarket::market::v1::BarData* bar_;
      ::hqmarket::market::v1::MarketStatusData* market_status_;
      ::hqmarket::market::v1::ProviderStatusData* provider_status_;
      ::hqmarket::market::v1::QueryRequest* query_request_;
      ::hqmarket::market::v1::QueryResponse* query_response_;
    } payload_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t _oneof_case_[1];
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_request_2frequest_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// RequestData

// .request.RequestType type = 1;
inline void RequestData::clear_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = 0;
}
inline ::request::RequestType RequestData::type() const {
  // @@protoc_insertion_point(field_get:request.RequestData.type)
  return _internal_type();
}
inline void RequestData::set_type(::request::RequestType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:request.RequestData.type)
}
inline ::request::RequestType RequestData::_internal_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::request::RequestType>(_impl_.type_);
}
inline void RequestData::_internal_set_type(::request::RequestType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = value;
}

// string cmd = 2;
inline void RequestData::clear_cmd() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cmd_.ClearToEmpty();
}
inline const std::string& RequestData::cmd() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:request.RequestData.cmd)
  return _internal_cmd();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void RequestData::set_cmd(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cmd_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:request.RequestData.cmd)
}
inline std::string* RequestData::mutable_cmd() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_cmd();
  // @@protoc_insertion_point(field_mutable:request.RequestData.cmd)
  return _s;
}
inline const std::string& RequestData::_internal_cmd() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.cmd_.Get();
}
inline void RequestData::_internal_set_cmd(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cmd_.Set(value, GetArena());
}
inline std::string* RequestData::_internal_mutable_cmd() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.cmd_.Mutable( GetArena());
}
inline std::string* RequestData::release_cmd() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:request.RequestData.cmd)
  return _impl_.cmd_.Release();
}
inline void RequestData::set_allocated_cmd(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cmd_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.cmd_.IsDefault()) {
    _impl_.cmd_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:request.RequestData.cmd)
}

// map<string, string> extra = 3;
inline int RequestData::_internal_extra_size() const {
  return _internal_extra().size();
}
inline int RequestData::extra_size() const {
  return _internal_extra_size();
}
inline void RequestData::clear_extra() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.extra_.Clear();
}
inline const ::google::protobuf::Map<std::string, std::string>& RequestData::_internal_extra() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.extra_.GetMap();
}
inline const ::google::protobuf::Map<std::string, std::string>& RequestData::extra() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:request.RequestData.extra)
  return _internal_extra();
}
inline ::google::protobuf::Map<std::string, std::string>* RequestData::_internal_mutable_extra() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.extra_.MutableMap();
}
inline ::google::protobuf::Map<std::string, std::string>* RequestData::mutable_extra() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_map:request.RequestData.extra)
  return _internal_mutable_extra();
}

// map<string, string> ret = 4;
inline int RequestData::_internal_ret_size() const {
  return _internal_ret().size();
}
inline int RequestData::ret_size() const {
  return _internal_ret_size();
}
inline void RequestData::clear_ret() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ret_.Clear();
}
inline const ::google::protobuf::Map<std::string, std::string>& RequestData::_internal_ret() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ret_.GetMap();
}
inline const ::google::protobuf::Map<std::string, std::string>& RequestData::ret() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:request.RequestData.ret)
  return _internal_ret();
}
inline ::google::protobuf::Map<std::string, std::string>* RequestData::_internal_mutable_ret() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.ret_.MutableMap();
}
inline ::google::protobuf::Map<std::string, std::string>* RequestData::mutable_ret() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_map:request.RequestData.ret)
  return _internal_mutable_ret();
}

// uint64 id = 5;
inline void RequestData::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = ::uint64_t{0u};
}
inline ::uint64_t RequestData::id() const {
  // @@protoc_insertion_point(field_get:request.RequestData.id)
  return _internal_id();
}
inline void RequestData::set_id(::uint64_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:request.RequestData.id)
}
inline ::uint64_t RequestData::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_;
}
inline void RequestData::_internal_set_id(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = value;
}

// .hqmarket.market.v1.AuthRequest auth_request = 10;
inline bool RequestData::has_auth_request() const {
  return payload_case() == kAuthRequest;
}
inline bool RequestData::_internal_has_auth_request() const {
  return payload_case() == kAuthRequest;
}
inline void RequestData::set_has_auth_request() {
  _impl_._oneof_case_[0] = kAuthRequest;
}
inline ::hqmarket::market::v1::AuthRequest* RequestData::release_auth_request() {
  // @@protoc_insertion_point(field_release:request.RequestData.auth_request)
  if (payload_case() == kAuthRequest) {
    clear_has_payload();
    auto* temp = _impl_.payload_.auth_request_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.auth_request_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::hqmarket::market::v1::AuthRequest& RequestData::_internal_auth_request() const {
  return payload_case() == kAuthRequest ? *_impl_.payload_.auth_request_ : reinterpret_cast<::hqmarket::market::v1::AuthRequest&>(::hqmarket::market::v1::_AuthRequest_default_instance_);
}
inline const ::hqmarket::market::v1::AuthRequest& RequestData::auth_request() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:request.RequestData.auth_request)
  return _internal_auth_request();
}
inline ::hqmarket::market::v1::AuthRequest* RequestData::unsafe_arena_release_auth_request() {
  // @@protoc_insertion_point(field_unsafe_arena_release:request.RequestData.auth_request)
  if (payload_case() == kAuthRequest) {
    clear_has_payload();
    auto* temp = _impl_.payload_.auth_request_;
    _impl_.payload_.auth_request_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void RequestData::unsafe_arena_set_allocated_auth_request(::hqmarket::market::v1::AuthRequest* value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_auth_request();
    _impl_.payload_.auth_request_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:request.RequestData.auth_request)
}
inline ::hqmarket::market::v1::AuthRequest* RequestData::_internal_mutable_auth_request() {
  if (payload_case() != kAuthRequest) {
    clear_payload();
    set_has_auth_request();
    _impl_.payload_.auth_request_ =
        ::google::protobuf::Message::DefaultConstruct<::hqmarket::market::v1::AuthRequest>(GetArena());
  }
  return _impl_.payload_.auth_request_;
}
inline ::hqmarket::market::v1::AuthRequest* RequestData::mutable_auth_request() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::hqmarket::market::v1::AuthRequest* _msg = _internal_mutable_auth_request();
  // @@protoc_insertion_point(field_mutable:request.RequestData.auth_request)
  return _msg;
}

// .hqmarket.market.v1.SubscribeRequest subscribe_request = 11;
inline bool RequestData::has_subscribe_request() const {
  return payload_case() == kSubscribeRequest;
}
inline bool RequestData::_internal_has_subscribe_request() const {
  return payload_case() == kSubscribeRequest;
}
inline void RequestData::set_has_subscribe_request() {
  _impl_._oneof_case_[0] = kSubscribeRequest;
}
inline ::hqmarket::market::v1::SubscribeRequest* RequestData::release_subscribe_request() {
  // @@protoc_insertion_point(field_release:request.RequestData.subscribe_request)
  if (payload_case() == kSubscribeRequest) {
    clear_has_payload();
    auto* temp = _impl_.payload_.subscribe_request_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.subscribe_request_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::hqmarket::market::v1::SubscribeRequest& RequestData::_internal_subscribe_request() const {
  return payload_case() == kSubscribeRequest ? *_impl_.payload_.subscribe_request_ : reinterpret_cast<::hqmarket::market::v1::SubscribeRequest&>(::hqmarket::market::v1::_SubscribeRequest_default_instance_);
}
inline const ::hqmarket::market::v1::SubscribeRequest& RequestData::subscribe_request() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:request.RequestData.subscribe_request)
  return _internal_subscribe_request();
}
inline ::hqmarket::market::v1::SubscribeRequest* RequestData::unsafe_arena_release_subscribe_request() {
  // @@protoc_insertion_point(field_unsafe_arena_release:request.RequestData.subscribe_request)
  if (payload_case() == kSubscribeRequest) {
    clear_has_payload();
    auto* temp = _impl_.payload_.subscribe_request_;
    _impl_.payload_.subscribe_request_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void RequestData::unsafe_arena_set_allocated_subscribe_request(::hqmarket::market::v1::SubscribeRequest* value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_subscribe_request();
    _impl_.payload_.subscribe_request_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:request.RequestData.subscribe_request)
}
inline ::hqmarket::market::v1::SubscribeRequest* RequestData::_internal_mutable_subscribe_request() {
  if (payload_case() != kSubscribeRequest) {
    clear_payload();
    set_has_subscribe_request();
    _impl_.payload_.subscribe_request_ =
        ::google::protobuf::Message::DefaultConstruct<::hqmarket::market::v1::SubscribeRequest>(GetArena());
  }
  return _impl_.payload_.subscribe_request_;
}
inline ::hqmarket::market::v1::SubscribeRequest* RequestData::mutable_subscribe_request() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::hqmarket::market::v1::SubscribeRequest* _msg = _internal_mutable_subscribe_request();
  // @@protoc_insertion_point(field_mutable:request.RequestData.subscribe_request)
  return _msg;
}

// .hqmarket.market.v1.UnsubscribeRequest unsubscribe_request = 12;
inline bool RequestData::has_unsubscribe_request() const {
  return payload_case() == kUnsubscribeRequest;
}
inline bool RequestData::_internal_has_unsubscribe_request() const {
  return payload_case() == kUnsubscribeRequest;
}
inline void RequestData::set_has_unsubscribe_request() {
  _impl_._oneof_case_[0] = kUnsubscribeRequest;
}
inline ::hqmarket::market::v1::UnsubscribeRequest* RequestData::release_unsubscribe_request() {
  // @@protoc_insertion_point(field_release:request.RequestData.unsubscribe_request)
  if (payload_case() == kUnsubscribeRequest) {
    clear_has_payload();
    auto* temp = _impl_.payload_.unsubscribe_request_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.unsubscribe_request_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::hqmarket::market::v1::UnsubscribeRequest& RequestData::_internal_unsubscribe_request() const {
  return payload_case() == kUnsubscribeRequest ? *_impl_.payload_.unsubscribe_request_ : reinterpret_cast<::hqmarket::market::v1::UnsubscribeRequest&>(::hqmarket::market::v1::_UnsubscribeRequest_default_instance_);
}
inline const ::hqmarket::market::v1::UnsubscribeRequest& RequestData::unsubscribe_request() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:request.RequestData.unsubscribe_request)
  return _internal_unsubscribe_request();
}
inline ::hqmarket::market::v1::UnsubscribeRequest* RequestData::unsafe_arena_release_unsubscribe_request() {
  // @@protoc_insertion_point(field_unsafe_arena_release:request.RequestData.unsubscribe_request)
  if (payload_case() == kUnsubscribeRequest) {
    clear_has_payload();
    auto* temp = _impl_.payload_.unsubscribe_request_;
    _impl_.payload_.unsubscribe_request_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void RequestData::unsafe_arena_set_allocated_unsubscribe_request(::hqmarket::market::v1::UnsubscribeRequest* value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_unsubscribe_request();
    _impl_.payload_.unsubscribe_request_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:request.RequestData.unsubscribe_request)
}
inline ::hqmarket::market::v1::UnsubscribeRequest* RequestData::_internal_mutable_unsubscribe_request() {
  if (payload_case() != kUnsubscribeRequest) {
    clear_payload();
    set_has_unsubscribe_request();
    _impl_.payload_.unsubscribe_request_ =
        ::google::protobuf::Message::DefaultConstruct<::hqmarket::market::v1::UnsubscribeRequest>(GetArena());
  }
  return _impl_.payload_.unsubscribe_request_;
}
inline ::hqmarket::market::v1::UnsubscribeRequest* RequestData::mutable_unsubscribe_request() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::hqmarket::market::v1::UnsubscribeRequest* _msg = _internal_mutable_unsubscribe_request();
  // @@protoc_insertion_point(field_mutable:request.RequestData.unsubscribe_request)
  return _msg;
}

// .hqmarket.market.v1.SubscriptionAck subscription_ack = 13;
inline bool RequestData::has_subscription_ack() const {
  return payload_case() == kSubscriptionAck;
}
inline bool RequestData::_internal_has_subscription_ack() const {
  return payload_case() == kSubscriptionAck;
}
inline void RequestData::set_has_subscription_ack() {
  _impl_._oneof_case_[0] = kSubscriptionAck;
}
inline ::hqmarket::market::v1::SubscriptionAck* RequestData::release_subscription_ack() {
  // @@protoc_insertion_point(field_release:request.RequestData.subscription_ack)
  if (payload_case() == kSubscriptionAck) {
    clear_has_payload();
    auto* temp = _impl_.payload_.subscription_ack_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.subscription_ack_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::hqmarket::market::v1::SubscriptionAck& RequestData::_internal_subscription_ack() const {
  return payload_case() == kSubscriptionAck ? *_impl_.payload_.subscription_ack_ : reinterpret_cast<::hqmarket::market::v1::SubscriptionAck&>(::hqmarket::market::v1::_SubscriptionAck_default_instance_);
}
inline const ::hqmarket::market::v1::SubscriptionAck& RequestData::subscription_ack() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:request.RequestData.subscription_ack)
  return _internal_subscription_ack();
}
inline ::hqmarket::market::v1::SubscriptionAck* RequestData::unsafe_arena_release_subscription_ack() {
  // @@protoc_insertion_point(field_unsafe_arena_release:request.RequestData.subscription_ack)
  if (payload_case() == kSubscriptionAck) {
    clear_has_payload();
    auto* temp = _impl_.payload_.subscription_ack_;
    _impl_.payload_.subscription_ack_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void RequestData::unsafe_arena_set_allocated_subscription_ack(::hqmarket::market::v1::SubscriptionAck* value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_subscription_ack();
    _impl_.payload_.subscription_ack_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:request.RequestData.subscription_ack)
}
inline ::hqmarket::market::v1::SubscriptionAck* RequestData::_internal_mutable_subscription_ack() {
  if (payload_case() != kSubscriptionAck) {
    clear_payload();
    set_has_subscription_ack();
    _impl_.payload_.subscription_ack_ =
        ::google::protobuf::Message::DefaultConstruct<::hqmarket::market::v1::SubscriptionAck>(GetArena());
  }
  return _impl_.payload_.subscription_ack_;
}
inline ::hqmarket::market::v1::SubscriptionAck* RequestData::mutable_subscription_ack() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::hqmarket::market::v1::SubscriptionAck* _msg = _internal_mutable_subscription_ack();
  // @@protoc_insertion_point(field_mutable:request.RequestData.subscription_ack)
  return _msg;
}

// .hqmarket.market.v1.QuoteData quote = 14;
inline bool RequestData::has_quote() const {
  return payload_case() == kQuote;
}
inline bool RequestData::_internal_has_quote() const {
  return payload_case() == kQuote;
}
inline void RequestData::set_has_quote() {
  _impl_._oneof_case_[0] = kQuote;
}
inline ::hqmarket::market::v1::QuoteData* RequestData::release_quote() {
  // @@protoc_insertion_point(field_release:request.RequestData.quote)
  if (payload_case() == kQuote) {
    clear_has_payload();
    auto* temp = _impl_.payload_.quote_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.quote_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::hqmarket::market::v1::QuoteData& RequestData::_internal_quote() const {
  return payload_case() == kQuote ? *_impl_.payload_.quote_ : reinterpret_cast<::hqmarket::market::v1::QuoteData&>(::hqmarket::market::v1::_QuoteData_default_instance_);
}
inline const ::hqmarket::market::v1::QuoteData& RequestData::quote() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:request.RequestData.quote)
  return _internal_quote();
}
inline ::hqmarket::market::v1::QuoteData* RequestData::unsafe_arena_release_quote() {
  // @@protoc_insertion_point(field_unsafe_arena_release:request.RequestData.quote)
  if (payload_case() == kQuote) {
    clear_has_payload();
    auto* temp = _impl_.payload_.quote_;
    _impl_.payload_.quote_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void RequestData::unsafe_arena_set_allocated_quote(::hqmarket::market::v1::QuoteData* value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_quote();
    _impl_.payload_.quote_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:request.RequestData.quote)
}
inline ::hqmarket::market::v1::QuoteData* RequestData::_internal_mutable_quote() {
  if (payload_case() != kQuote) {
    clear_payload();
    set_has_quote();
    _impl_.payload_.quote_ =
        ::google::protobuf::Message::DefaultConstruct<::hqmarket::market::v1::QuoteData>(GetArena());
  }
  return _impl_.payload_.quote_;
}
inline ::hqmarket::market::v1::QuoteData* RequestData::mutable_quote() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::hqmarket::market::v1::QuoteData* _msg = _internal_mutable_quote();
  // @@protoc_insertion_point(field_mutable:request.RequestData.quote)
  return _msg;
}

// .hqmarket.market.v1.DepthData depth = 15;
inline bool RequestData::has_depth() const {
  return payload_case() == kDepth;
}
inline bool RequestData::_internal_has_depth() const {
  return payload_case() == kDepth;
}
inline void RequestData::set_has_depth() {
  _impl_._oneof_case_[0] = kDepth;
}
inline ::hqmarket::market::v1::DepthData* RequestData::release_depth() {
  // @@protoc_insertion_point(field_release:request.RequestData.depth)
  if (payload_case() == kDepth) {
    clear_has_payload();
    auto* temp = _impl_.payload_.depth_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.depth_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::hqmarket::market::v1::DepthData& RequestData::_internal_depth() const {
  return payload_case() == kDepth ? *_impl_.payload_.depth_ : reinterpret_cast<::hqmarket::market::v1::DepthData&>(::hqmarket::market::v1::_DepthData_default_instance_);
}
inline const ::hqmarket::market::v1::DepthData& RequestData::depth() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:request.RequestData.depth)
  return _internal_depth();
}
inline ::hqmarket::market::v1::DepthData* RequestData::unsafe_arena_release_depth() {
  // @@protoc_insertion_point(field_unsafe_arena_release:request.RequestData.depth)
  if (payload_case() == kDepth) {
    clear_has_payload();
    auto* temp = _impl_.payload_.depth_;
    _impl_.payload_.depth_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void RequestData::unsafe_arena_set_allocated_depth(::hqmarket::market::v1::DepthData* value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_depth();
    _impl_.payload_.depth_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:request.RequestData.depth)
}
inline ::hqmarket::market::v1::DepthData* RequestData::_internal_mutable_depth() {
  if (payload_case() != kDepth) {
    clear_payload();
    set_has_depth();
    _impl_.payload_.depth_ =
        ::google::protobuf::Message::DefaultConstruct<::hqmarket::market::v1::DepthData>(GetArena());
  }
  return _impl_.payload_.depth_;
}
inline ::hqmarket::market::v1::DepthData* RequestData::mutable_depth() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::hqmarket::market::v1::DepthData* _msg = _internal_mutable_depth();
  // @@protoc_insertion_point(field_mutable:request.RequestData.depth)
  return _msg;
}

// .hqmarket.market.v1.TradeData trade = 16;
inline bool RequestData::has_trade() const {
  return payload_case() == kTrade;
}
inline bool RequestData::_internal_has_trade() const {
  return payload_case() == kTrade;
}
inline void RequestData::set_has_trade() {
  _impl_._oneof_case_[0] = kTrade;
}
inline ::hqmarket::market::v1::TradeData* RequestData::release_trade() {
  // @@protoc_insertion_point(field_release:request.RequestData.trade)
  if (payload_case() == kTrade) {
    clear_has_payload();
    auto* temp = _impl_.payload_.trade_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.trade_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::hqmarket::market::v1::TradeData& RequestData::_internal_trade() const {
  return payload_case() == kTrade ? *_impl_.payload_.trade_ : reinterpret_cast<::hqmarket::market::v1::TradeData&>(::hqmarket::market::v1::_TradeData_default_instance_);
}
inline const ::hqmarket::market::v1::TradeData& RequestData::trade() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:request.RequestData.trade)
  return _internal_trade();
}
inline ::hqmarket::market::v1::TradeData* RequestData::unsafe_arena_release_trade() {
  // @@protoc_insertion_point(field_unsafe_arena_release:request.RequestData.trade)
  if (payload_case() == kTrade) {
    clear_has_payload();
    auto* temp = _impl_.payload_.trade_;
    _impl_.payload_.trade_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void RequestData::unsafe_arena_set_allocated_trade(::hqmarket::market::v1::TradeData* value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_trade();
    _impl_.payload_.trade_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:request.RequestData.trade)
}
inline ::hqmarket::market::v1::TradeData* RequestData::_internal_mutable_trade() {
  if (payload_case() != kTrade) {
    clear_payload();
    set_has_trade();
    _impl_.payload_.trade_ =
        ::google::protobuf::Message::DefaultConstruct<::hqmarket::market::v1::TradeData>(GetArena());
  }
  return _impl_.payload_.trade_;
}
inline ::hqmarket::market::v1::TradeData* RequestData::mutable_trade() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::hqmarket::market::v1::TradeData* _msg = _internal_mutable_trade();
  // @@protoc_insertion_point(field_mutable:request.RequestData.trade)
  return _msg;
}

// .hqmarket.market.v1.BarData bar = 17;
inline bool RequestData::has_bar() const {
  return payload_case() == kBar;
}
inline bool RequestData::_internal_has_bar() const {
  return payload_case() == kBar;
}
inline void RequestData::set_has_bar() {
  _impl_._oneof_case_[0] = kBar;
}
inline ::hqmarket::market::v1::BarData* RequestData::release_bar() {
  // @@protoc_insertion_point(field_release:request.RequestData.bar)
  if (payload_case() == kBar) {
    clear_has_payload();
    auto* temp = _impl_.payload_.bar_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.bar_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::hqmarket::market::v1::BarData& RequestData::_internal_bar() const {
  return payload_case() == kBar ? *_impl_.payload_.bar_ : reinterpret_cast<::hqmarket::market::v1::BarData&>(::hqmarket::market::v1::_BarData_default_instance_);
}
inline const ::hqmarket::market::v1::BarData& RequestData::bar() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:request.RequestData.bar)
  return _internal_bar();
}
inline ::hqmarket::market::v1::BarData* RequestData::unsafe_arena_release_bar() {
  // @@protoc_insertion_point(field_unsafe_arena_release:request.RequestData.bar)
  if (payload_case() == kBar) {
    clear_has_payload();
    auto* temp = _impl_.payload_.bar_;
    _impl_.payload_.bar_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void RequestData::unsafe_arena_set_allocated_bar(::hqmarket::market::v1::BarData* value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_bar();
    _impl_.payload_.bar_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:request.RequestData.bar)
}
inline ::hqmarket::market::v1::BarData* RequestData::_internal_mutable_bar() {
  if (payload_case() != kBar) {
    clear_payload();
    set_has_bar();
    _impl_.payload_.bar_ =
        ::google::protobuf::Message::DefaultConstruct<::hqmarket::market::v1::BarData>(GetArena());
  }
  return _impl_.payload_.bar_;
}
inline ::hqmarket::market::v1::BarData* RequestData::mutable_bar() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::hqmarket::market::v1::BarData* _msg = _internal_mutable_bar();
  // @@protoc_insertion_point(field_mutable:request.RequestData.bar)
  return _msg;
}

// .hqmarket.market.v1.MarketStatusData market_status = 18;
inline bool RequestData::has_market_status() const {
  return payload_case() == kMarketStatus;
}
inline bool RequestData::_internal_has_market_status() const {
  return payload_case() == kMarketStatus;
}
inline void RequestData::set_has_market_status() {
  _impl_._oneof_case_[0] = kMarketStatus;
}
inline ::hqmarket::market::v1::MarketStatusData* RequestData::release_market_status() {
  // @@protoc_insertion_point(field_release:request.RequestData.market_status)
  if (payload_case() == kMarketStatus) {
    clear_has_payload();
    auto* temp = _impl_.payload_.market_status_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.market_status_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::hqmarket::market::v1::MarketStatusData& RequestData::_internal_market_status() const {
  return payload_case() == kMarketStatus ? *_impl_.payload_.market_status_ : reinterpret_cast<::hqmarket::market::v1::MarketStatusData&>(::hqmarket::market::v1::_MarketStatusData_default_instance_);
}
inline const ::hqmarket::market::v1::MarketStatusData& RequestData::market_status() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:request.RequestData.market_status)
  return _internal_market_status();
}
inline ::hqmarket::market::v1::MarketStatusData* RequestData::unsafe_arena_release_market_status() {
  // @@protoc_insertion_point(field_unsafe_arena_release:request.RequestData.market_status)
  if (payload_case() == kMarketStatus) {
    clear_has_payload();
    auto* temp = _impl_.payload_.market_status_;
    _impl_.payload_.market_status_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void RequestData::unsafe_arena_set_allocated_market_status(::hqmarket::market::v1::MarketStatusData* value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_market_status();
    _impl_.payload_.market_status_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:request.RequestData.market_status)
}
inline ::hqmarket::market::v1::MarketStatusData* RequestData::_internal_mutable_market_status() {
  if (payload_case() != kMarketStatus) {
    clear_payload();
    set_has_market_status();
    _impl_.payload_.market_status_ =
        ::google::protobuf::Message::DefaultConstruct<::hqmarket::market::v1::MarketStatusData>(GetArena());
  }
  return _impl_.payload_.market_status_;
}
inline ::hqmarket::market::v1::MarketStatusData* RequestData::mutable_market_status() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::hqmarket::market::v1::MarketStatusData* _msg = _internal_mutable_market_status();
  // @@protoc_insertion_point(field_mutable:request.RequestData.market_status)
  return _msg;
}

// .hqmarket.market.v1.ProviderStatusData provider_status = 19;
inline bool RequestData::has_provider_status() const {
  return payload_case() == kProviderStatus;
}
inline bool RequestData::_internal_has_provider_status() const {
  return payload_case() == kProviderStatus;
}
inline void RequestData::set_has_provider_status() {
  _impl_._oneof_case_[0] = kProviderStatus;
}
inline ::hqmarket::market::v1::ProviderStatusData* RequestData::release_provider_status() {
  // @@protoc_insertion_point(field_release:request.RequestData.provider_status)
  if (payload_case() == kProviderStatus) {
    clear_has_payload();
    auto* temp = _impl_.payload_.provider_status_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.provider_status_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::hqmarket::market::v1::ProviderStatusData& RequestData::_internal_provider_status() const {
  return payload_case() == kProviderStatus ? *_impl_.payload_.provider_status_ : reinterpret_cast<::hqmarket::market::v1::ProviderStatusData&>(::hqmarket::market::v1::_ProviderStatusData_default_instance_);
}
inline const ::hqmarket::market::v1::ProviderStatusData& RequestData::provider_status() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:request.RequestData.provider_status)
  return _internal_provider_status();
}
inline ::hqmarket::market::v1::ProviderStatusData* RequestData::unsafe_arena_release_provider_status() {
  // @@protoc_insertion_point(field_unsafe_arena_release:request.RequestData.provider_status)
  if (payload_case() == kProviderStatus) {
    clear_has_payload();
    auto* temp = _impl_.payload_.provider_status_;
    _impl_.payload_.provider_status_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void RequestData::unsafe_arena_set_allocated_provider_status(::hqmarket::market::v1::ProviderStatusData* value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_provider_status();
    _impl_.payload_.provider_status_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:request.RequestData.provider_status)
}
inline ::hqmarket::market::v1::ProviderStatusData* RequestData::_internal_mutable_provider_status() {
  if (payload_case() != kProviderStatus) {
    clear_payload();
    set_has_provider_status();
    _impl_.payload_.provider_status_ =
        ::google::protobuf::Message::DefaultConstruct<::hqmarket::market::v1::ProviderStatusData>(GetArena());
  }
  return _impl_.payload_.provider_status_;
}
inline ::hqmarket::market::v1::ProviderStatusData* RequestData::mutable_provider_status() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::hqmarket::market::v1::ProviderStatusData* _msg = _internal_mutable_provider_status();
  // @@protoc_insertion_point(field_mutable:request.RequestData.provider_status)
  return _msg;
}

// .hqmarket.market.v1.QueryRequest query_request = 20;
inline bool RequestData::has_query_request() const {
  return payload_case() == kQueryRequest;
}
inline bool RequestData::_internal_has_query_request() const {
  return payload_case() == kQueryRequest;
}
inline void RequestData::set_has_query_request() {
  _impl_._oneof_case_[0] = kQueryRequest;
}
inline ::hqmarket::market::v1::QueryRequest* RequestData::release_query_request() {
  // @@protoc_insertion_point(field_release:request.RequestData.query_request)
  if (payload_case() == kQueryRequest) {
    clear_has_payload();
    auto* temp = _impl_.payload_.query_request_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.query_request_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::hqmarket::market::v1::QueryRequest& RequestData::_internal_query_request() const {
  return payload_case() == kQueryRequest ? *_impl_.payload_.query_request_ : reinterpret_cast<::hqmarket::market::v1::QueryRequest&>(::hqmarket::market::v1::_QueryRequest_default_instance_);
}
inline const ::hqmarket::market::v1::QueryRequest& RequestData::query_request() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:request.RequestData.query_request)
  return _internal_query_request();
}
inline ::hqmarket::market::v1::QueryRequest* RequestData::unsafe_arena_release_query_request() {
  // @@protoc_insertion_point(field_unsafe_arena_release:request.RequestData.query_request)
  if (payload_case() == kQueryRequest) {
    clear_has_payload();
    auto* temp = _impl_.payload_.query_request_;
    _impl_.payload_.query_request_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void RequestData::unsafe_arena_set_allocated_query_request(::hqmarket::market::v1::QueryRequest* value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_query_request();
    _impl_.payload_.query_request_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:request.RequestData.query_request)
}
inline ::hqmarket::market::v1::QueryRequest* RequestData::_internal_mutable_query_request() {
  if (payload_case() != kQueryRequest) {
    clear_payload();
    set_has_query_request();
    _impl_.payload_.query_request_ =
        ::google::protobuf::Message::DefaultConstruct<::hqmarket::market::v1::QueryRequest>(GetArena());
  }
  return _impl_.payload_.query_request_;
}
inline ::hqmarket::market::v1::QueryRequest* RequestData::mutable_query_request() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::hqmarket::market::v1::QueryRequest* _msg = _internal_mutable_query_request();
  // @@protoc_insertion_point(field_mutable:request.RequestData.query_request)
  return _msg;
}

// .hqmarket.market.v1.QueryResponse query_response = 21;
inline bool RequestData::has_query_response() const {
  return payload_case() == kQueryResponse;
}
inline bool RequestData::_internal_has_query_response() const {
  return payload_case() == kQueryResponse;
}
inline void RequestData::set_has_query_response() {
  _impl_._oneof_case_[0] = kQueryResponse;
}
inline ::hqmarket::market::v1::QueryResponse* RequestData::release_query_response() {
  // @@protoc_insertion_point(field_release:request.RequestData.query_response)
  if (payload_case() == kQueryResponse) {
    clear_has_payload();
    auto* temp = _impl_.payload_.query_response_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.query_response_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::hqmarket::market::v1::QueryResponse& RequestData::_internal_query_response() const {
  return payload_case() == kQueryResponse ? *_impl_.payload_.query_response_ : reinterpret_cast<::hqmarket::market::v1::QueryResponse&>(::hqmarket::market::v1::_QueryResponse_default_instance_);
}
inline const ::hqmarket::market::v1::QueryResponse& RequestData::query_response() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:request.RequestData.query_response)
  return _internal_query_response();
}
inline ::hqmarket::market::v1::QueryResponse* RequestData::unsafe_arena_release_query_response() {
  // @@protoc_insertion_point(field_unsafe_arena_release:request.RequestData.query_response)
  if (payload_case() == kQueryResponse) {
    clear_has_payload();
    auto* temp = _impl_.payload_.query_response_;
    _impl_.payload_.query_response_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void RequestData::unsafe_arena_set_allocated_query_response(::hqmarket::market::v1::QueryResponse* value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_query_response();
    _impl_.payload_.query_response_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:request.RequestData.query_response)
}
inline ::hqmarket::market::v1::QueryResponse* RequestData::_internal_mutable_query_response() {
  if (payload_case() != kQueryResponse) {
    clear_payload();
    set_has_query_response();
    _impl_.payload_.query_response_ =
        ::google::protobuf::Message::DefaultConstruct<::hqmarket::market::v1::QueryResponse>(GetArena());
  }
  return _impl_.payload_.query_response_;
}
inline ::hqmarket::market::v1::QueryResponse* RequestData::mutable_query_response() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::hqmarket::market::v1::QueryResponse* _msg = _internal_mutable_query_response();
  // @@protoc_insertion_point(field_mutable:request.RequestData.query_response)
  return _msg;
}

inline bool RequestData::has_payload() const {
  return payload_case() != PAYLOAD_NOT_SET;
}
inline void RequestData::clear_has_payload() {
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}
inline RequestData::PayloadCase RequestData::payload_case() const {
  return RequestData::PayloadCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace request


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::request::RequestType> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::request::RequestType>() {
  return ::request::RequestType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // request_2frequest_2eproto_2epb_2eh
